/**
 * @moolam/contract-conformance — Stage 1 private package.
 *
 * Executable obligation surfaces for `@moolam/contracts` MUST clauses.
 */

export {
  DuplicateObligationIdError,
  ObligationRegistry,
  ObligationViolation,
  UnknownObligationIdError,
  createObligationContext,
  defineObligation,
  invokeObligation,
  type ConformanceEvent,
  type ConformanceObligationEvent,
  type ConformanceRegistryEvent,
  type CreateObligationContextParams,
  type Obligation,
  type ObligationCatalog,
  type ObligationCatalogEntry,
  type ObligationContext,
  type ObligationRegistryOptions,
} from "./registry.js";

export {
  aggregateExitCode,
  buildRunReport,
  formatHumanReport,
  formatJsonReport,
  formatReport,
  writeReport,
  type ConformanceRunReport,
  type FailureAttribution,
  type ObligationVerdict,
  type ReportFormat,
  type VerdictOutcome,
} from "./report.js";

export {
  BINDING_CERTIFICATION_REPORT_SCHEMA_VERSION,
  CERTIFICATION_CHECK_DEADLINE_MS,
  DEFAULT_OBLIGATION_DEADLINE_MS,
  ObligationDeadlineError,
  runConformance,
  type ConformanceRunnerEvent,
  type FactoryContext,
  type ImplementationFactory,
  type ImplementationTeardown,
  type RunConformanceOptions,
} from "./runner.js";

export {
  parseConformanceArgv,
  runConformanceCli,
  type CliIo,
  type ParsedCliArgs,
} from "./cli.js";

export {
  WIRE_OBLIGATION_IDS,
  createSyncRequestValidator,
  createWireShapeRegistry,
  defineSyncRequestSubjectIsolationObligation,
  defineSyncRequestValidatesObligation,
  formatAjvErrors,
  loadWireFixtureBundle,
  registerWireShapeObligations,
  scopedValidSyncRequest,
  validSyncRequestProducer,
  violationSyncRequestProducer,
  wireFixtureBundlePath,
  type SyncRequestProducer,
  type WireFixtureBundle,
  type WireFixtureViolation,
} from "./obligations/wire.js";

export {
  EPISODIC_HALF_LIFE_MS,
  MEMORY_OBLIGATION_IDS,
  MEMORY_VIOLATION_FIXTURES,
  MUST_CONCURRENT_SUBJECTS,
  MUST_KIND_AWARE_DECAY,
  MUST_REMEMBER_DURABLE,
  createAsyncWriteAfterResolveMemoryHarnessFactory,
  createDecayingCorrectionsMemoryHarnessFactory,
  createDurableMemoryHarnessFactory,
  createLeakySubjectMemoryHarnessFactory,
  createMemoryDecayObligationRegistry,
  createMemoryDurabilityIsolationRegistry,
  createMemoryObligationsRegistry,
  createNoDecayMemoryHarnessFactory,
  createSharedSubjectStoreMemoryHarnessFactory,
  createUniformDecayMemoryHarnessFactory,
  createVolatileMemoryHarnessFactory,
  defineMemoryConcurrentSubjectsObligation,
  defineMemoryDecayObligation,
  defineMemoryDurabilityObligation,
  kindAwareDecayFactor,
  listMemoryViolationFixtures,
  parseCreatedAtMs,
  registerMemoryDecayObligation,
  registerMemoryDurabilityAndIsolationObligations,
  registerMemoryObligations,
  type MemoryConformanceHarness,
  type MemoryViolationFixture,
} from "./obligations/memory.js";

export {
  MUST_CONSTRAINTS_SURFACE,
  MUST_TRACE_NON_EMPTY,
  REASONING_OBLIGATION_IDS,
  REASONING_VIOLATION_FIXTURES,
  UNVERIFIABLE_CONSTRAINT_PREFIX,
  buildConstraintSurfacingProbeRequest,
  buildTraceProbeRequest,
  createConstraintSurfacingObligationRegistry,
  createConstraintSwallowingReasoningHarnessFactory,
  createDroppedConstraintReasoningHarnessFactory,
  createEmptyTraceReasoningHarnessFactory,
  createFillerTraceReasoningHarnessFactory,
  createMandatoryTraceObligationRegistry,
  createParaphrasedConstraintReasoningHarnessFactory,
  createReasoningObligationsRegistry,
  createTracedReasoningHarnessFactory,
  defineConstraintSurfacingObligation,
  defineMandatoryTraceObligation,
  isFillerStepStatement,
  listReasoningViolationFixtures,
  registerConstraintSurfacingObligation,
  registerMandatoryTraceObligation,
  registerReasoningObligations,
  unverifiableConstraintToken,
  type ReasoningConformanceHarness,
  type ReasoningViolationFixture,
} from "./obligations/reasoning.js";

export {
  KNOWLEDGE_CHECK_CLOCK_MS,
  KNOWLEDGE_OBLIGATION_IDS,
  KNOWLEDGE_PASSAGE_SCAN_LIMIT,
  KNOWLEDGE_VIOLATION_FIXTURES,
  MUST_ASOF_TRUTHFUL,
  MUST_BUNDLED_OFFLINE,
  MUST_CITATION_RESOLVABLE,
  buildAsOfProbeQuery,
  buildCitationProbeQuery,
  buildOfflineProbeQuery,
  createCitationPresenceObligationRegistry,
  createCitedKnowledgeHarnessFactory,
  createFutureAsOfKnowledgeHarnessFactory,
  createKnowledgeObligationsRegistry,
  createOfflineLiarKnowledgeHarnessFactory,
  createOfflineStalenessObligationRegistry,
  createUncitedKnowledgeHarnessFactory,
  createUncitedPassageKnowledgeHarnessFactory,
  createUnresolvedSourceKnowledgeHarnessFactory,
  defineBundledOfflineObligation,
  defineCitationPresenceObligation,
  defineTruthfulAsOfObligation,
  listKnowledgeViolationFixtures,
  parseAsOfMs,
  registerCitationPresenceObligation,
  registerKnowledgeObligations,
  registerOfflineAndStalenessObligations,
  type KnowledgeConformanceHarness,
  type KnowledgeViolationFixture,
} from "./obligations/knowledge.js";

export {
  MUST_ARG_VALIDATION,
  MUST_DEADLINE_ENFORCEMENT,
  MUST_WRITE_AHEAD_AUDIT,
  TOOL_AUDIT_SCAN_LIMIT,
  TOOL_DEADLINE_PROBE_MS,
  TOOL_DEADLINE_WATCHDOG_MS,
  TOOL_HANG_PROBE_NAME,
  TOOL_OBLIGATION_IDS,
  TOOL_PROBE_NAME,
  TOOL_READ_PROBE_NAME,
  TOOL_VIOLATION_FIXTURES,
  TOOL_WRITE_PROBE_NAME,
  buildDeadlineInvocationId,
  buildInvalidToolArguments,
  buildToolInvocationId,
  buildValidToolArguments,
  buildWriteAheadInvocationId,
  createArgValidationObligationRegistry,
  createAuditAfterEffectToolHarnessFactory,
  createDeadlineEnforcementObligationRegistry,
  createHangingToolHarnessFactory,
  createOpaqueErrorToolHarnessFactory,
  createThrowingToolHarnessFactory,
  createToolObligationsRegistry,
  createValidatingToolHarnessFactory,
  createWriteAheadAuditObligationRegistry,
  createWriteAheadToolHarnessFactory,
  defineArgValidationObligation,
  defineDeadlineEnforcementObligation,
  defineWriteAheadAuditObligation,
  hasSchemaErrorDetails,
  hasTimeoutErrorDetails,
  listToolViolationFixtures,
  registerArgValidationObligation,
  registerDeadlineEnforcementObligation,
  registerToolObligations,
  registerWriteAheadAuditObligation,
  type ToolAuditPhase,
  type ToolAuditRecord,
  type ToolAuditSink,
  type ToolConformanceHarness,
  type ToolViolationFixture,
} from "./obligations/tool.js";

export {
  DESKTOP_CERTIFICATION_MODEL_OBLIGATION_IDS,
  ANDROID_CERTIFICATION_MODEL_OBLIGATION_IDS,
  APPLE_SILICON_CERTIFICATION_MODEL_OBLIGATION_IDS,
  MODEL_EMBED_PROBE_COUNT,
  MODEL_OBLIGATION_IDS,
  MODEL_REFERENCE_EMBED_DIM,
  MODEL_STREAM_CHUNK_LIMIT,
  MUST_EMBED_DIMENSION_STABLE,
  MUST_LOCALITY_TRUTHFUL,
  MUST_STREAM_DELTAS,
  buildModelEmbedProbeTexts,
  buildModelProbeMessages,
  collectStreamChunks,
  createCumulativeStreamModelHarnessFactory,
  createEmbedDimensionStableObligationRegistry,
  createLocalityLiarModelHarnessFactory,
  createLocalityTruthfulObligationRegistry,
  createModelObligationsRegistry,
  createSelfHostedModelHarnessFactory,
  createStableModelHarnessFactory,
  createStreamDeltasObligationRegistry,
  createUnstableEmbedModelHarnessFactory,
  defineEmbedDimensionStableObligation,
  defineLocalityTruthfulObligation,
  defineStreamDeltasObligation,
  isCumulativeStreamFrame,
  registerEmbedDimensionStableObligation,
  registerLocalityTruthfulObligation,
  registerModelObligations,
  registerStreamDeltasObligation,
  type ModelConformanceHarness,
} from "./obligations/model.js";

export {
  MUST_LANGUAGE_FALLBACK,
  MUST_TRANSCRIBE_PARTIALS,
  SPEECH_OBLIGATION_IDS,
  SPEECH_PROBE_SAMPLE_RATE_HZ,
  SPEECH_STREAM_CHUNK_LIMIT,
  SPEECH_UNSUPPORTED_LANGUAGE,
  buildSpeechProbeAudioChunk,
  collectAudioChunks,
  collectTranscriptSegments,
  createFinalOnlySpeechHarnessFactory,
  createLanguageFallbackObligationRegistry,
  createNoFallbackSpeechHarnessFactory,
  createSpeechObligationsRegistry,
  createStreamingSpeechHarnessFactory,
  createTranscribePartialsObligationRegistry,
  createUndeclaredLanguagesSpeechHarnessFactory,
  defineLanguageFallbackObligation,
  defineTranscribePartialsObligation,
  hasPartialBeforeFinal,
  registerLanguageFallbackObligation,
  registerSpeechObligations,
  registerTranscribePartialsObligation,
  speechProbeAudioStream,
  type SpeechConformanceHarness,
} from "./obligations/speech.js";

export {
  MUST_REJECT_OVERSIZED,
  MUST_SCHEMA_VALID_JSON,
  VISION_OBLIGATION_IDS,
  VISION_REFERENCE_MAX_INPUT_BYTES,
  VISION_SCHEMA_KEY_SCAN_LIMIT,
  buildVisionProbeInput,
  buildVisionProbeInstruction,
  buildVisionProbeResponseSchema,
  createAcceptOversizedVisionHarnessFactory,
  createInvalidSchemaAnswerVisionHarnessFactory,
  createProcessBeforeRejectVisionHarnessFactory,
  createRejectOversizedObligationRegistry,
  createSchemaValidJsonObligationRegistry,
  createStrictVisionHarnessFactory,
  createUntypedSizeErrorVisionHarnessFactory,
  createVisionObligationsRegistry,
  createVisionSizeLimitError,
  defineRejectOversizedObligation,
  defineSchemaValidJsonObligation,
  isTypedSizeLimitError,
  registerRejectOversizedObligation,
  registerSchemaValidJsonObligation,
  registerVisionObligations,
  validateAnswerAgainstSchema,
  type VisionConformanceHarness,
} from "./obligations/vision.js";

export {
  MUST_CYCLIC_REVISE,
  MUST_REVISION_UPDATES_RATIONALE,
  PLANNING_OBLIGATION_IDS,
  PLANNING_STEP_SCAN_LIMIT,
  PLANNING_VIOLATION_FIXTURES,
  buildPlanningProbeContext,
  buildPlanningProbeGoals,
  createCyclicPlanningHarnessFactory,
  createCyclicReviseObligationRegistry,
  createNoLoopBackPlanningHarnessFactory,
  createPlanningObligationsRegistry,
  createRevisionUpdatesRationaleObligationRegistry,
  createSilentRationalePlanningHarnessFactory,
  defineCyclicReviseObligation,
  defineRevisionUpdatesRationaleObligation,
  detectsLoopBack,
  listPlanningViolationFixtures,
  registerCyclicReviseObligation,
  registerPlanningObligations,
  registerRevisionUpdatesRationaleObligation,
  type PlanningConformanceHarness,
  type PlanningViolationFixture,
} from "./obligations/planning.js";

export {
  CAST_05_MIN_ROOT_FRICTION_SAMPLES,
  CAST_OBLIGATION_IDS,
  CAST_ROOT_SCAN_LIMIT,
  CAST_VIOLATION_FIXTURES,
  CAST_COLDSTART_GOLDENS_RELPATH,
  CAST_COLDSTART_GOLDENS_SCHEMA,
  MUST_COLD_START_ADVANCE_BLOCKED,
  buildColdStartProbeInput,
  createCastObligationsRegistry,
  createColdStartAdvanceBlockedObligationRegistry,
  createCompliantCastHarnessFactory,
  createPrematureAdvanceCastHarnessFactory,
  defineColdStartAdvanceBlockedObligation,
  listCastViolationFixtures,
  registerColdStartAdvanceBlockedObligation,
  type CastConformanceHarness,
  type CastViolationFixture,
} from "./obligations/cast.js";

export {
  MUST_DURABLE_BEFORE_RESOLVE,
  MUST_FAILED_TASK_NON_BLOCKING,
  MUST_FLUSH_BEFORE_DISPOSE,
  MUST_INITIALIZE_IDEMPOTENT,
  MUST_STABLE_SCHEDULER_ORDER,
  MUST_SUBSCRIBER_THROW_ISOLATION,
  RUNTIME_OBLIGATION_IDS,
  RUNTIME_SCAN_LIMIT,
  RUNTIME_SUBSCRIBER_ERROR_TYPE,
  RUNTIME_VIOLATION_FIXTURES,
  buildRuntimeProbeKey,
  createDisposeWithoutFlushRuntimeHarnessFactory,
  createDurableBeforeResolveObligationRegistry,
  createExecuteBeforeDurableRuntimeHarnessFactory,
  createFailBlocksQueueRuntimeHarnessFactory,
  createFailedTaskNonBlockingObligationRegistry,
  createFlushBeforeDisposeObligationRegistry,
  createInitializeIdempotentObligationRegistry,
  createNonIdempotentInitRuntimeHarnessFactory,
  createPublishRethrowsRuntimeHarnessFactory,
  createReferenceRuntimeHarnessFactory,
  createRuntimeObligationsRegistry,
  createStableSchedulerOrderObligationRegistry,
  createSubscriberThrowIsolationObligationRegistry,
  createUnstableSchedulerRuntimeHarnessFactory,
  defineDurableBeforeResolveObligation,
  defineFailedTaskNonBlockingObligation,
  defineFlushBeforeDisposeObligation,
  defineInitializeIdempotentObligation,
  defineStableSchedulerOrderObligation,
  defineSubscriberThrowIsolationObligation,
  listRuntimeViolationFixtures,
  registerDurableBeforeResolveObligation,
  registerFailedTaskNonBlockingObligation,
  registerFlushBeforeDisposeObligation,
  registerInitializeIdempotentObligation,
  registerRuntimeObligations,
  registerStableSchedulerOrderObligation,
  registerSubscriberThrowIsolationObligation,
  type RuntimeConformanceHarness,
  type RuntimeViolationFixture,
} from "./obligations/runtime.js";

export {
  REMAINING_VIOLATION_FIXTURES,
  listRemainingViolationFixtures,
  type RemainingDomain,
  type RemainingHarness,
  type RemainingViolationFixture,
} from "./obligations/remaining_fixtures.js";

export {
  DEFAULT_EGRESS_TURN_DEADLINE_MS,
  DEFAULT_MAX_EGRESS_RECORDS,
  EGRESS_INTERCEPTION_SCOPE,
  EgressCallerDeniedError,
  EgressTurnDeadlineError,
  callerAllowsSubject,
  classifyEgressDestination,
  createLoopbackPermitEgressMockAgent,
  isInsideEgressRecordingTurn,
  normalizeEgressHost,
  withEgressRecordingTurn,
  type EgressAttemptRecord,
  type EgressDestinationClass,
  type EgressInitiatorBinding,
  type EgressInterceptionScope,
  type EgressRecordingApi,
  type EgressRecordingOptions,
  type EgressTurnRecord,
  type EgressTurnResult,
  type LocalityCallerBinding,
  type LocalityEgressEvent,
  type PayloadClassMarker,
} from "./locality/harness.js";

export {
  DEFAULT_SOVEREIGN_LOCALITY_POLICY,
  LOCALITY_ASSERT_SCAN_LIMIT,
  LOCALITY_OBLIGATION_IDS,
  MUST_LOCALITY_GATE_PER_DATA_CLASS,
  allowedLocalitiesFor,
  assertLocality,
  createCompliantLocalityHarnessFactory,
  createCrossSubjectEgressViolationFactory,
  createLocalityPolicyObligationsRegistry,
  createRegulatedThirdPartyViolationFactory,
  defineRegulatedStaysLocalObligation,
  defineSubjectBoundEgressObligation,
  destinationToAllowedLocality,
  registerLocalityPolicyObligations,
  registerRegulatedStaysLocalObligation,
  registerSubjectBoundEgressObligation,
  type AllowedLocality,
  type LocalityAssertEvent,
  type LocalityAssertionResult,
  type LocalityConformanceHarness,
  type LocalityPolicy,
  type LocalityViolation,
  type LocalityViolationCode,
} from "./locality/harness.js";

export {
  MUST_CONSERVATIVE_UNRESOLVED_REFUSAL,
  MUST_REFUSALS_AS_CONSTRAINTS,
  MUST_REFUSAL_DECLINE,
  REFUSAL_OBLIGATION_IDS,
  REFUSAL_PROBE_LEGAL,
  REFUSAL_PROBE_PRESCRIPTION,
  REFUSAL_VIOLATION_FIXTURES,
  buildConservativeUnresolvedProbeInput,
  buildInScopeProbeInput,
  buildRefusalDeclineProbeInput,
  createCompliantRefusalHarnessFactory,
  createConstraintsDroppedHarnessFactory,
  createDeclineIgnoringHarnessFactory,
  createRefusalDeclinePathObligationRegistry,
  createRefusalObligationsRegistry,
  createRefusalSwallowingHarnessFactory,
  createRefusalSwallowingReasoning,
  createScopeAwareReasoning,
  defineConservativeUnresolvedObligation,
  defineRefusalDeclinePathObligation,
  defineRefusalsAsConstraintsObligation,
  formatDeclineReply,
  listRefusalViolationFixtures,
  registerConservativeUnresolvedObligation,
  registerRefusalDeclinePathObligation,
  registerRefusalObligations,
  registerRefusalsAsConstraintsObligation,
  unresolvedRefusalCategories,
  withConstraintRecording,
  type RefusalConformanceHarness,
  type RefusalViolationFixture,
} from "./obligations/refusals.js";
