/**
 * @moolam/observability — OpenTelemetry bridge for Sutra hosts.
 *
 * Exporter choice is configuration (OTLP / console / noop). Consumers call
 * `initObservability()` once at process start; turn-stage wiring and EventBus
 * enrichment live in `otel_bridge`; SyncEngine spans live in `sync_audit`.
 * Domain event Zod schemas live in `event_catalog` .
 */

export {
  ALLOWED_BUS_PAYLOAD_KEYS,
  ALLOWED_TURN_ATTR_KEYS,
  BUS_EVENT_ATTR_LIMIT,
  TURN_BUS_EVENT_TYPES,
  TURN_STAGE_NAMES,
  STAGE_DURATION_HISTOGRAM,
  DropOnFailureSpanExporter,
  ObservabilityConfigError,
  assertSpanExportPrivacy,
  assertTurnAttrKeysAllowed,
  createTurnInstrumentation,
  enrichActiveSpanFromBusEvent,
  findRawContentLeaks,
  getObservability,
  hashOpCode,
  initObservability,
  publishToolBusEvent,
  publishTurnCompleted,
  publishSyncOutcome,
  resolveExporterKind,
  sanitizeBusPayload,
  shutdownObservability,
  subscribeEventBusToSpans,
  wireEdgeAgentEventBus,
  EDGE_LIFECYCLE_READY,
  TURN_COMPLETED,
  SYNC_OUTCOME,
  type CreateTurnInstrumentationOptions,
  type ExporterKind,
  type InitObservabilityOptions,
  type ObservabilityHandle,
  type PrivacyProbeSet,
  type SpanPrivacyLeak,
  type TurnInstrumentation,
  type TurnSpanAttributes,
  type TurnStageName,
  type TurnStageRunner,
  type PublishSyncOutcomeArgs,
  type PublishTurnCompletedArgs,
  type WireEdgeAgentEventBusOptions,
  type WiredEdgeAgentEventBus,
} from "./otel_bridge.js";

export {
  ALLOWED_SYNC_ATTR_KEYS,
  KNOWN_SYNC_ADVISORY_CODES,
  SYNC_ADVISORY_EVENT,
  SYNC_ADVISORY_EVENT_LIMIT,
  SYNC_WIRE_TRACEPARENT,
  SYNC_WIRE_TRACESTATE,
  createSyncInstrumentation,
  extractSyncWireContext,
  getDefaultSyncInstrumentation,
  injectSyncWireHeaders,
  normalizeSyncWireCarrier,
  recordSyncAdvisoryEvents,
  withContinuedSyncSpan,
  type SyncAdvisoryForSpan,
  type SyncConnectivity,
  type SyncInstrumentation,
  type SyncSpanAttributes,
  type SyncSpanSeries,
  type SyncTerminalOutcome,
  type SyncTerminalRecord,
} from "./sync_audit.js";

export {
  CATALOG_EVENT_TYPES,
  CATALOG_STAGE_OUTCOMES,
  CATALOG_SYNC_ADVISORY_CODES,
  CATALOG_SYNC_OUTCOMES,
  CATALOG_TOOL_STATUSES,
  CATALOG_TURN_STAGES,
  CATALOG_WORKED_EXAMPLES,
  CatalogContractError,
  EVENT_CATALOG_DOC_RELPATH,
  EVENT_CATALOG_VERSION,
  EVENT_PAYLOAD_SCHEMAS,
  EVENT_SCHEMA_DOT_TYPE,
  EVENT_SCHEMA_EXPORT_MAP,
  EVENT_SCHEMA_TYPE_NAMES,
  FORBIDDEN_CATALOG_PAYLOAD_KEYS,
  ValidatingEventBus,
  assertCatalogPayload,
  catalogEventEnvelopeSchema,
  createCatalogPublishValidator,
  createValidatingEventBus,
  eventAtSchema,
  eventRuntimeSubscriberErrorSchema,
  eventSyncAdvisorySchema,
  eventSyncOutcomeSchema,
  eventHarnessMeterSchema,
  eventToolInvokedSchema,
  eventToolResultSchema,
  eventTurnCompletedSchema,
  eventTurnFrictionSummarySchema,
  eventTurnStageEndSchema,
  eventTurnStageStartSchema,
  turnCompletedPayloadSchema,
  getPayloadSchema,
  isCatalogEventType,
  parseCatalogEvent,
  resolvePublishValidationMode,
  runtimeSubscriberErrorPayloadSchema,
  syncAdvisoryPayloadSchema,
  syncOutcomePayloadSchema,
  harnessMeterPayloadSchema,
  toolInvokedPayloadSchema,
  toolResultPayloadSchema,
  turnFrictionSummaryPayloadSchema,
  turnStageEndPayloadSchema,
  turnStageStartPayloadSchema,
  type CatalogEventType,
  type CatalogPayloadByType,
  type CreateValidatingEventBusOptions,
  type EventSchemaTypeName,
} from "./event_catalog.js";

export {
  HEALING_AUDIT_ATTR_KEYS,
  HEALING_AUDIT_OUTCOME_EVENT,
  HEALING_AUDIT_WRITE_AHEAD_EVENT,
  HEALING_ACTION_KINDS,
  HEALING_FAILURE_CLASSES,
  HEALING_METRICS_RECEIPT_LIMIT,
  HEALING_METRIC_ATTR_KEYS,
  HEALING_REMEDIATIONS_ATTEMPTED_COUNTER,
  HEALING_REMEDIATIONS_DISABLED_COUNTER,
  HEALING_REMEDIATIONS_SUCCEEDED_COUNTER,
  HEALING_TIME_TO_RESOLUTION_HISTOGRAM,
  HealingMetricsContractError,
  assertHealingMetricAttrKeysAllowed,
  createHealingMetricsSink,
  createInMemoryHealingMetricsSink,
  emitHealingAuditOutcome,
  emitHealingAuditWriteAheadAck,
  toHealingAuditWriteAheadSpineEvent,
  type HealingActionKind,
  type HealingAuditRecordForSpine,
  type HealingAuditOutcomeSpineEvent,
  type HealingAuditWriteAheadSpineEvent,
  type HealingFailureClass,
  type HealingMetricOutcome,
  type HealingMetricsEvent,
  type HealingMetricsFailureClass,
  type HealingMetricsSink,
  type HealingMetricsSnapshot,
} from "./healing_metrics.js";
