/**
 * sutra-bindings-slm — on-device SLM bindings (llama.cpp / GGUF).
 */

export {
  GGUF_MAGIC,
  LLAMA_CPP_PINNED_REVISION,
  parseGgufMetadata,
  writeMinimalGguf,
  type GgufMetadata,
} from "./gguf_metadata.js";

export {
  createInProcessLlamaCppBackend,
  type LlamaCppGenerateNativeParams,
  type LlamaCppGenerateNativeResult,
  type LlamaCppNativeBackend,
  type LlamaCppNativeHandle,
} from "./native_ffi.js";

export {
  OLLAMA_DEFAULT_BASE_URL,
  OLLAMA_DEFAULT_MODEL,
  createOllamaLlamaCppBackend,
  probeOllamaReachable,
  resolveOllamaConfigFromEnv,
  type OllamaConfigFromEnv,
  type OllamaLlamaCppBackendOptions,
  type OllamaReachability,
  type OllamaReachabilityError,
} from "./ollama_backend.js";

export {
  LlamaCppSlmRuntime,
  type LlamaCppSlmRuntimeOptions,
  type LlamaCppTelemetryEvent,
  type LlamaCppTelemetryOp,
} from "./llamacpp_runtime.js";

export {
  createLlamaCppModelAdapter,
  createLlamaCppModelAdapterHarnessFactory,
  loadLlamaCppModelAdapter,
  toStreamDeltas,
  type CreateLlamaCppModelAdapterHarnessOptions,
  type LlamaCppModelAdapterBundle,
  type LlamaCppModelAdapterOptions,
} from "./model_adapter.js";

export {
  CERTIFICATION_REPORT_FILENAME,
  CERTIFICATION_REPORT_SCHEMA_RELPATH,
  CERTIFICATION_REPORT_SCHEMA_VERSION,
  CERTIFY_PHASE_ORDER,
  CERT_PROFILE_REGISTRY_RELPATH,
  CERT_PROFILE_REGISTRY_SCHEMA_VERSION,
  CERT_PROFILE_SCHEMA_VERSION,
  CERT_REGISTRY_PROFILE_IDS,
  CERTIFICATION_DIR,
  DESKTOP_PROFILE_PATH,
  CertifyValidationError,
  assertCertificationReportValid,
  certProfileRegistryPath,
  certificationReportSchemaPath,
  defaultCertificationReportPath,
  ONE_COMMAND_PROVE_TARGETS,
  loadCertProfile,
  loadCertProfileRegistry,
  lookupCertProfileRegistryEntry,
  parseBindingsSlmArgv,
  proveOneCommandCertifyFlow,
  resolveProfilePath,
  runBindingsSlmCli,
  runCertifyProfile,
  runUnifiedCertifyOrchestration,
  sha256File,
  toUnifiedCertProfileInput,
  validateCertificationReport,
  writeCertifyReportArtifact,
  type CertProfile,
  type CertProfileRegistry,
  type CertProfileRegistryEntry,
  type CertRegistryProfileId,
  type CertifyAdapterFactory,
  type CertifyIo,
  type CertifyPhaseId,
  type CertifyReport,
  type CertifyResult,
  type OneCommandProveResult,
  type OneCommandProveTarget,
  type OneCommandProveTargetResult,
  type ProveOneCommandCertifyOptions,
  type RunCertifyProfileOptions,
  type RunUnifiedCertifyOptions,
  type UnifiedCertPhaseResult,
  type UnifiedCertProfileInput,
  type UnifiedCertificationReport,
} from "./certify.js";
export {
  proveLlamaCppOfflineDesktopTurn,
  OFFLINE_EDGE_GOLDEN_RELPATH,
  type OfflineTurnProofOptions,
  type OfflineTurnProofResult,
  type OfflineTurnProofTelemetry,
} from "./offline_turn_proof.js";

export {
  runOfflineEdgeLiveTurn,
  type OfflineEdgeLiveTurnOptions,
  type OfflineEdgeLiveTurnResult,
  type OfflineEdgeLiveTelemetry,
} from "./offline_turn_live.js";

export {
  MID_RANGE_DEVICE_PROFILE_PATH,
  ONNX_MOBILE_DEVICE_PROFILE_SCHEMA,
  ONNX_MOBILE_SUPPORTED_QUANT_FORMATS,
  ONNX_RUNTIME_MOBILE_PINNED_VERSION,
  OnnxSlmRuntime,
  createInProcessOnnxMobileBackend,
  loadMidRangeDeviceProfile,
  onnxCardSidecarPath,
  planOnnxMobileLoad,
  readOnnxModelCardFile,
  type OnnxExecutionProvider,
  type OnnxLoadPlan,
  type OnnxMobileDeviceProfile,
  type OnnxMobileModelCardFile,
  type OnnxMobileNativeBackend,
  type OnnxMobileTelemetryEvent,
  type OnnxMobileTelemetryOp,
  type OnnxSlmRuntimeOptions,
} from "./onnx_mobile_runtime.js";

export {
  createOnnxModelAdapter,
  createOnnxModelAdapterHarnessFactory,
  loadOnnxModelAdapter,
  type CreateOnnxModelAdapterHarnessOptions,
  type OnnxModelAdapterBundle,
  type OnnxModelAdapterOptions,
} from "./onnx_model_adapter.js";

export {
  ANDROID_CERTIFICATION_MODEL_OBLIGATION_IDS,
  ANDROID_PROFILE_PATH,
  loadOnnxAndroidCertProfile,
  runOnnxAndroidCertifyFromProfilePath,
  runOnnxAndroidCertifyProfile,
  type OnnxAndroidCertProfile,
  type OnnxAndroidCertReport,
  type RunOnnxAndroidCertifyOptions,
} from "./onnx_certify.js";

export {
  MLX_APPLE_SILICON_FIXTURE_RELPATH,
  MLX_PINNED_REVISION,
  MlxSlmRuntime,
  createInProcessMlxMetalBackend,
  mapMlxFinishReason,
  mlxAppleSiliconFixturePath,
  mlxCardSidecarPath,
  probeMlxPlatform,
  readMlxModelCardFile,
  type MlxGenerateNativeParams,
  type MlxGenerateNativeResult,
  type MlxHostProbe,
  type MlxModelCardFile,
  type MlxNativeBackend,
  type MlxNativeHandle,
  type MlxPlatformProbeResult,
  type MlxSlmRuntimeOptions,
  type MlxTelemetryEvent,
  type MlxTelemetryOp,
} from "./mlx_runtime.js";

export {
  createMlxModelAdapter,
  createMlxModelAdapterHarnessFactory,
  loadMlxModelAdapter,
  type CreateMlxModelAdapterHarnessOptions,
  type MlxModelAdapterBundle,
  type MlxModelAdapterOptions,
} from "./mlx_model_adapter.js";

export {
  APPLE_SILICON_CERTIFICATION_MODEL_OBLIGATION_IDS,
  APPLE_SILICON_PROFILE_PATH,
  loadMlxAppleSiliconCertProfile,
  runMlxAppleSiliconCertifyFromProfilePath,
  runMlxAppleSiliconCertifyProfile,
  type MlxAppleSiliconCertProfile,
  type MlxAppleSiliconCertReport,
  type RunMlxAppleSiliconCertifyOptions,
} from "./mlx_certify.js";

export {
  AICORE_ABSENT_FIXTURE_RELPATH,
  AICORE_CAPABLE_FIXTURE_RELPATH,
  AICORE_DOWNLOADING_FIXTURE_RELPATH,
  AICORE_SCENARIOS_DIR_RELPATH,
  AicoreSlmRuntime,
  EdgeSlmLoadPlanError,
  UNAVAILABLE_SLM_CARD,
  UnavailableSlmRuntime,
  aicoreAbsentFixturePath,
  aicoreCapableFixturePath,
  aicoreDownloadingFixturePath,
  aicoreScenarioPath,
  buildAicoreCapability,
  createAicoreSlmRuntimeCandidate,
  createInProcessAicoreBackend,
  createInProcessAicoreBackendFromFixture,
  isUnavailableSlmRuntime,
  loadAicoreCapabilityFixture,
  loadAicoreDeviceScenario,
  mapAicoreFinishReason,
  planEdgeSlmRuntimeLoad,
  probeAicoreCapability,
  type AicoreCapability,
  type AicoreDeviceScenario,
  type AicoreGenerateNativeParams,
  type AicoreGenerateNativeResult,
  type AicoreHostProbe,
  type AicoreMemoryClass,
  type AicoreModelDescriptor,
  type AicoreModelReadiness,
  type AicoreNativeBackend,
  type AicoreNativeHandle,
  type AicoreSlmRuntimeOptions,
  type AicoreTelemetryEvent,
  type AicoreTelemetryOp,
  type CreateAicoreCandidateOptions,
  type EdgeSlmCandidate,
  type EdgeSlmLoadPlan,
  type EdgeSlmLoadPlanTelemetry,
  type EdgeSlmLoadSkip,
  type EdgeSlmLoadSkipReason,
  type PlanEdgeSlmRuntimeLoadOptions,
  type UnavailableSlmRuntimeOptions,
} from "./aicore_seam.js";

export {
  ADAPTER_DELTA_BYTE_LIMIT,
  ADAPTER_DELTA_SCHEMA_VERSION,
  ADAPTER_TRAIN_SEAM_VERSION,
  ADAPTER_DELTA_ELEMS_PER_RANK,
  AdapterTrainContractError,
  LORA_DEFAULT_ALPHA,
  LORA_DEFAULT_CLIP_EPSILON,
  LORA_DEFAULT_RANK,
  LoraAdapterTrainer,
  assertAdapterOnlyUpdate,
  contentAddressDelta,
  pinAdapterTrainLineage,
  proveLoraAdapterUpdateMicroRun,
  synthesizeLoraAdapterDeltaBytes,
  validateLoraUpdateConfig,
  type AdapterDeltaArtifact,
  type AdapterTrainFailureClass,
  type AdapterTrainLineagePin,
  type AdapterTrainTelemetryEvent,
  type LoraAdapterUpdateResult,
  type LoraUpdateConfig,
} from "./adapter_train.js";

export {
  ADAPTER_DELTA_MANIFEST_SCHEMA_VERSION,
  ADAPTER_LOAD_BYTE_LIMIT,
  ADAPTER_LOAD_SEAM_VERSION,
  ADAPTER_LOAD_SESSION_PIN_LIMIT,
  ADAPTER_PRECISION_FORMATS,
  AdapterLoadContractError,
  SlmRuntimeAdapterLoader,
  contentAddressAdapterBlob,
  proveAdapterLoadApplyMicroRun,
  proveAdapterLoadVerifyMicroRun,
  verifyAdapterDeltaForLoad,
  verifyPackedAdapterDelta,
  type AdapterDeltaManifestView,
  type AdapterLoadApplyResult,
  type AdapterLoadFailureClass,
  type AdapterLoadRuntimePins,
  type AdapterLoadTelemetryEvent,
  type AdapterLoadVerifyResult,
  type AdapterPrecisionFormat,
  type AppliedAdapterState,
} from "./adapter_load.js";

export {
  ADAPTER_CACHE_BYTE_LIMIT,
  ADAPTER_CACHE_ENTRY_LIMIT,
  ADAPTER_CACHE_SCHEMA_VERSION,
  AdapterCacheContractError,
  ResumableDurableAdapterCache,
  VerifiedAdapterCache,
  type AdapterCacheFailureClass,
  type AdapterCacheTelemetryEvent,
  type VerifiedAdapterCacheEntry,
} from "./adapter_cache.js";
