/**
 * Friction aggregation rollup — subject/concept summaries from FrictionSample[].
 *
 * Behavioral metadata only (same privacy rule as FrictionSample). Exportable
 * rollups require `consentRecordId` referencing an active opt-in consent scope.
 * Storage stays sovereign-side; cross-boundary batches attach consent explicitly.
 */

import { z } from "zod";
import {
  compareHLC,
  frictionSampleSchema,
  hlcSchema,
  type FrictionSample,
  type HLCTimestamp,
} from "./contract.js";

/** Aggregation rollup schema id — bump MINOR for additive field additions only. */
export const FRICTION_AGGREGATION_SCHEMA_VERSION = "aggregation.v1" as const;

/**
 * Repo-relative path to the committed JSON Schema export.
 * Regenerated by `pnpm --filter @moolam/sync-protocol schemas:export`.
 */
export const FRICTION_AGGREGATION_COMMITTED_SCHEMA_RELPATH =
  "schemas/FrictionAggregationRollup.json" as const;

/** Soft caps (NFR — bounded scans of friction logs / concept maps). */
export const AGGREGATION_SAMPLE_INPUT_LIMIT = 4096;
export const AGGREGATION_CONCEPT_LIMIT = 512;
export const AGGREGATION_ID_LIMIT = 128;

export const AGGREGATION_LOCALITIES = Object.freeze([
  "on-device",
  "self-hosted",
] as const);

export type AggregationLocality = (typeof AGGREGATION_LOCALITIES)[number];

export const AGGREGATION_CONSENT_SCOPES = Object.freeze(["aggregation"] as const);

export type AggregationConsentScope = (typeof AGGREGATION_CONSENT_SCOPES)[number];

/** Active opt-in ledger entry referenced by rollup.consentRecordId. */
export type AggregationConsentRecord = {
  consentRecordId: string;
  subjectId: string;
  optedIn: boolean;
  /** False after revocation — mid-batch export must reject. */
  active: boolean;
  scope: AggregationConsentScope;
  /** Opaque capture time (ISO or HLC) — never utterance text. */
  recordedAt: string;
  /**
   * Soft expiry marker (ISO or HLC). When present and past, export rejects
   * with `consent_expired` even if `active` remains true.
   */
  expiresAt?: string | undefined;
};

export type ConceptFrictionRollup = {
  conceptId: string;
  sampleCount: number;
  hesitationMsSum: number;
  hesitationMsMax: number;
  inputVelocitySum: number;
  revisionCountSum: number;
  assistanceRequestedCount: number;
  outcomes: {
    correct: number;
    partial: number;
    incorrect: number;
    ungraded: number;
  };
};

/**
 * Subject-level friction aggregation rollup.
 * No raw keystroke / prompt / utterance fields — metadata counts only.
 */
export type FrictionAggregationRollup = {
  schemaVersion: typeof FRICTION_AGGREGATION_SCHEMA_VERSION;
  subjectId: string;
  deviceId: string;
  /** Required — references an active opt-in AggregationConsentRecord. */
  consentRecordId: string;
  locality: AggregationLocality;
  rolledUpAt: HLCTimestamp;
  sampleCount: number;
  concepts: ConceptFrictionRollup[];
};

const FORBIDDEN_CONTENT_KEYS = Object.freeze([
  "keystrokes",
  "rawKeystrokes",
  "utterance",
  "prompt",
  "completion",
  "reply",
  "arguments",
  "toolArgs",
]);

const outcomeCountsSchema = z
  .object({
    correct: z.number().int().nonnegative(),
    partial: z.number().int().nonnegative(),
    incorrect: z.number().int().nonnegative(),
    ungraded: z.number().int().nonnegative(),
  })
  .strict();

export const conceptFrictionRollupSchema = z
  .object({
    conceptId: z.string().min(1).max(AGGREGATION_ID_LIMIT),
    sampleCount: z.number().int().nonnegative().max(AGGREGATION_SAMPLE_INPUT_LIMIT),
    hesitationMsSum: z.number().int().nonnegative(),
    hesitationMsMax: z.number().int().nonnegative(),
    inputVelocitySum: z.number().nonnegative(),
    revisionCountSum: z.number().int().nonnegative(),
    assistanceRequestedCount: z.number().int().nonnegative(),
    outcomes: outcomeCountsSchema,
  })
  .strict() satisfies z.ZodType<ConceptFrictionRollup>;

export const frictionAggregationRollupSchema = z
  .object({
    schemaVersion: z.literal(FRICTION_AGGREGATION_SCHEMA_VERSION),
    subjectId: z.string().min(1).max(AGGREGATION_ID_LIMIT),
    deviceId: z.string().min(1).max(AGGREGATION_ID_LIMIT),
    consentRecordId: z.string().min(1).max(AGGREGATION_ID_LIMIT),
    locality: z.enum(AGGREGATION_LOCALITIES),
    rolledUpAt: hlcSchema,
    sampleCount: z.number().int().nonnegative().max(AGGREGATION_SAMPLE_INPUT_LIMIT),
    concepts: z.array(conceptFrictionRollupSchema).max(AGGREGATION_CONCEPT_LIMIT),
  })
  .strict()
  .superRefine((rec, ctx) => {
    for (const key of FORBIDDEN_CONTENT_KEYS) {
      if (Object.prototype.hasOwnProperty.call(rec, key)) {
        ctx.addIssue({
          code: "custom",
          path: [key],
          message: `raw content key '${key}' forbidden — behavioral metadata only`,
        });
      }
    }
    const conceptSum = rec.concepts.reduce((n, c) => n + c.sampleCount, 0);
    if (conceptSum !== rec.sampleCount) {
      ctx.addIssue({
        code: "custom",
        path: ["sampleCount"],
        message: "sampleCount must equal sum of concept sampleCount values",
      });
    }
  }) satisfies z.ZodType<FrictionAggregationRollup>;

export const aggregationConsentRecordSchema = z
  .object({
    consentRecordId: z.string().min(1).max(AGGREGATION_ID_LIMIT),
    subjectId: z.string().min(1).max(AGGREGATION_ID_LIMIT),
    optedIn: z.boolean(),
    active: z.boolean(),
    scope: z.enum(AGGREGATION_CONSENT_SCOPES),
    recordedAt: z.string().min(1).max(AGGREGATION_ID_LIMIT),
    /**
     * Soft expiry marker (ISO / HLC). When set and lexicographically before
     * `nowIso` (or wall now), export fails as consent_expired even if active.
     */
    expiresAt: z.string().min(1).max(AGGREGATION_ID_LIMIT).optional(),
  })
  .strict() satisfies z.ZodType<AggregationConsentRecord>;

export type AggregationFailureClass =
  | "validation"
  | "keystroke_forbidden"
  | "consent_missing"
  | "consent_denied"
  | "consent_revoked"
  | "consent_expired"
  | "consent_scope"
  | "cross_subject"
  | "sample_limit"
  | "concept_limit"
  | "write_failed";

/** Consent-gate failure classes that surface as AggregationConsentError. */
export const AGGREGATION_CONSENT_FAILURE_CLASSES = Object.freeze([
  "consent_missing",
  "consent_denied",
  "consent_revoked",
  "consent_expired",
  "consent_scope",
  "cross_subject",
] as const);

export type AggregationConsentFailureClass =
  (typeof AGGREGATION_CONSENT_FAILURE_CLASSES)[number];

/**
 * Typed consent-gate failure for aggregation export / rollup egress.
 * Never carries raw learner content — obligation + subjectId metadata only.
 */
export class AggregationConsentError extends Error {
  readonly obligation: AggregationConsentFailureClass;
  readonly subjectId: string | null;
  readonly consentRecordId: string | undefined;
  readonly deviceId: string | undefined;

  constructor(
    message: string,
    meta: {
      obligation: AggregationConsentFailureClass;
      subjectId?: string | null | undefined;
      consentRecordId?: string | undefined;
      deviceId?: string | undefined;
    },
  ) {
    super(message);
    this.name = "AggregationConsentError";
    this.obligation = meta.obligation;
    this.subjectId = meta.subjectId ?? null;
    this.consentRecordId = meta.consentRecordId;
    this.deviceId = meta.deviceId;
  }
}

export function isAggregationConsentFailure(
  failureClass: string,
): failureClass is AggregationConsentFailureClass {
  return (AGGREGATION_CONSENT_FAILURE_CLASSES as readonly string[]).includes(
    failureClass,
  );
}

/**
 * Raise a typed AggregationConsentError from a consent-gate rejection.
 * Non-consent failure classes stay as plain Error with the obligation named.
 */
export function raiseAggregationConsentError(input: {
  failureClass: AggregationFailureClass | string;
  detail: string;
  subjectId?: string | null | undefined;
  consentRecordId?: string | undefined;
  deviceId?: string | undefined;
}): never {
  if (isAggregationConsentFailure(input.failureClass)) {
    throw new AggregationConsentError(input.detail, {
      obligation: input.failureClass,
      ...(input.subjectId !== undefined ? { subjectId: input.subjectId } : {}),
      ...(input.consentRecordId !== undefined
        ? { consentRecordId: input.consentRecordId }
        : {}),
      ...(input.deviceId !== undefined ? { deviceId: input.deviceId } : {}),
    });
  }
  const err = new Error(input.detail);
  err.name = `AggregationContractError:${input.failureClass}`;
  throw err;
}

export type ParseFrictionAggregationAccepted = {
  ok: true;
  record: FrictionAggregationRollup;
  subjectId: string;
  deviceId: string;
};

export type ParseFrictionAggregationRejected = {
  ok: false;
  failureClass: AggregationFailureClass;
  subjectId: string | null;
  detail: string;
  issuePath?: string;
};

export type ParseFrictionAggregationResult =
  | ParseFrictionAggregationAccepted
  | ParseFrictionAggregationRejected;

function emptyOutcomes(): ConceptFrictionRollup["outcomes"] {
  return { correct: 0, partial: 0, incorrect: 0, ungraded: 0 };
}

/**
 * Idempotent merge of FrictionSample arrays by `capturedAt` — never double-count.
 * Prefer the lexicographically greater sample on collision (stable CRDT-style).
 */
export function dedupeFrictionSamplesByCapturedAt(
  samples: readonly FrictionSample[],
): FrictionSample[] {
  const byKey = new Map<string, FrictionSample>();
  for (const sample of samples) {
    const existing = byKey.get(sample.capturedAt);
    if (!existing) {
      byKey.set(sample.capturedAt, sample);
      continue;
    }
    // Prefer richer / later-encoded twin on identical HLC key.
    const prefer =
      JSON.stringify(sample).localeCompare(JSON.stringify(existing)) >= 0
        ? sample
        : existing;
    byKey.set(sample.capturedAt, prefer);
  }
  return [...byKey.values()].sort((a, b) => compareHLC(a.capturedAt, b.capturedAt));
}

export type BuildFrictionAggregationInput = {
  subjectId: string;
  deviceId: string;
  consentRecordId: string;
  locality: AggregationLocality;
  samples: readonly FrictionSample[];
  rolledUpAt: HLCTimestamp;
};

export type BuildFrictionAggregationResult =
  | { ok: true; record: FrictionAggregationRollup }
  | {
      ok: false;
      failureClass: AggregationFailureClass;
      subjectId: string | null;
      detail: string;
    };

/**
 * Build a subject/concept rollup from friction samples.
 * Validates each sample at the boundary; dedupes by capturedAt before counting.
 */
export function buildFrictionAggregationRollup(
  input: BuildFrictionAggregationInput,
): BuildFrictionAggregationResult {
  if (!input.subjectId || !input.deviceId || !input.consentRecordId) {
    return {
      ok: false,
      failureClass: "validation",
      subjectId: input.subjectId || null,
      detail: "subjectId, deviceId, and consentRecordId are required",
    };
  }
  if (input.samples.length > AGGREGATION_SAMPLE_INPUT_LIMIT) {
    return {
      ok: false,
      failureClass: "sample_limit",
      subjectId: input.subjectId,
      detail: `samples exceed AGGREGATION_SAMPLE_INPUT_LIMIT (${AGGREGATION_SAMPLE_INPUT_LIMIT})`,
    };
  }

  const validated: FrictionSample[] = [];
  for (const raw of input.samples) {
    const parsed = frictionSampleSchema.safeParse(raw);
    if (!parsed.success) {
      return {
        ok: false,
        failureClass: "validation",
        subjectId: input.subjectId,
        detail: "friction sample failed wire validation",
      };
    }
    validated.push(parsed.data);
  }

  const unique = dedupeFrictionSamplesByCapturedAt(validated);
  const byConcept = new Map<string, ConceptFrictionRollup>();

  for (const sample of unique) {
    let row = byConcept.get(sample.conceptId);
    if (!row) {
      if (byConcept.size >= AGGREGATION_CONCEPT_LIMIT) {
        return {
          ok: false,
          failureClass: "concept_limit",
          subjectId: input.subjectId,
          detail: `concepts exceed AGGREGATION_CONCEPT_LIMIT (${AGGREGATION_CONCEPT_LIMIT})`,
        };
      }
      row = {
        conceptId: sample.conceptId,
        sampleCount: 0,
        hesitationMsSum: 0,
        hesitationMsMax: 0,
        inputVelocitySum: 0,
        revisionCountSum: 0,
        assistanceRequestedCount: 0,
        outcomes: emptyOutcomes(),
      };
      byConcept.set(sample.conceptId, row);
    }
    row.sampleCount += 1;
    row.hesitationMsSum += sample.hesitationMs;
    row.hesitationMsMax = Math.max(row.hesitationMsMax, sample.hesitationMs);
    row.inputVelocitySum += sample.inputVelocity;
    row.revisionCountSum += sample.revisionCount;
    if (sample.assistanceRequested) row.assistanceRequestedCount += 1;
    row.outcomes[sample.outcome] += 1;
  }

  const concepts = [...byConcept.values()].sort((a, b) =>
    a.conceptId.localeCompare(b.conceptId),
  );

  const record: FrictionAggregationRollup = {
    schemaVersion: FRICTION_AGGREGATION_SCHEMA_VERSION,
    subjectId: input.subjectId,
    deviceId: input.deviceId,
    consentRecordId: input.consentRecordId,
    locality: input.locality,
    rolledUpAt: input.rolledUpAt,
    sampleCount: unique.length,
    concepts,
  };

  const gate = parseFrictionAggregationRollup(record);
  if (!gate.ok) {
    return {
      ok: false,
      failureClass: gate.failureClass,
      subjectId: gate.subjectId,
      detail: gate.detail,
    };
  }
  return { ok: true, record: gate.record };
}

/**
 * Attach consentRecordId to a pre-built rollup body after consent ledger check.
 * Rejects revoked / inactive / cross-subject consent at attachment time.
 */
export function attachAggregationConsent(
  body: Omit<FrictionAggregationRollup, "consentRecordId">,
  consent: AggregationConsentRecord,
): BuildFrictionAggregationResult {
  const consentParsed = aggregationConsentRecordSchema.safeParse(consent);
  if (!consentParsed.success) {
    return {
      ok: false,
      failureClass: "validation",
      subjectId: body.subjectId,
      detail: "consent record failed validation",
    };
  }
  const c = consentParsed.data;
  if (c.subjectId !== body.subjectId) {
    return {
      ok: false,
      failureClass: "cross_subject",
      subjectId: body.subjectId,
      detail: "consent subjectId must match rollup subjectId",
    };
  }
  if (c.scope !== "aggregation") {
    return {
      ok: false,
      failureClass: "consent_scope",
      subjectId: body.subjectId,
      detail: "consent scope must be aggregation",
    };
  }
  if (c.expiresAt !== undefined) {
    const now = new Date().toISOString();
    if (c.expiresAt < now) {
      return {
        ok: false,
        failureClass: "consent_expired",
        subjectId: body.subjectId,
        detail: "consent record expired",
      };
    }
  }
  if (!c.active) {
    return {
      ok: false,
      failureClass: "consent_revoked",
      subjectId: body.subjectId,
      detail: "consent record is not active",
    };
  }
  if (!c.optedIn) {
    return {
      ok: false,
      failureClass: "consent_denied",
      subjectId: body.subjectId,
      detail: "aggregation export requires optedIn === true",
    };
  }

  const attached = {
    ...body,
    consentRecordId: c.consentRecordId,
  };
  const gate = parseFrictionAggregationRollup(attached);
  if (!gate.ok) {
    return {
      ok: false,
      failureClass: gate.failureClass,
      subjectId: gate.subjectId,
      detail: gate.detail,
    };
  }
  return { ok: true, record: gate.record };
}

/**
 * Export gate — resolve consentRecordId to an active opt-in ledger entry.
 * Mid-batch revocation (active === false) rejects the batch.
 * Soft expiry (`expiresAt` in the past) rejects as consent_expired.
 */
export function assertAggregationExportConsent(
  rollup: FrictionAggregationRollup,
  resolveConsent: (
    consentRecordId: string,
  ) => AggregationConsentRecord | null | undefined,
  options: { nowIso?: string | undefined } = {},
):
  | { ok: true; subjectId: string; consentRecordId: string }
  | {
      ok: false;
      failureClass: AggregationFailureClass;
      subjectId: string | null;
      detail: string;
    } {
  if (!rollup.subjectId) {
    return {
      ok: false,
      failureClass: "validation",
      subjectId: null,
      detail: "subjectId required",
    };
  }
  if (!rollup.consentRecordId) {
    return {
      ok: false,
      failureClass: "consent_missing",
      subjectId: rollup.subjectId,
      detail: "consentRecordId required for aggregation export",
    };
  }

  let resolved: AggregationConsentRecord | null | undefined;
  try {
    resolved = resolveConsent(rollup.consentRecordId);
  } catch (err: unknown) {
    return {
      ok: false,
      failureClass: "validation",
      subjectId: rollup.subjectId,
      detail:
        err instanceof Error
          ? `consent resolve failed: ${err.name}`
          : "consent resolve failed",
    };
  }

  if (!resolved) {
    return {
      ok: false,
      failureClass: "consent_missing",
      subjectId: rollup.subjectId,
      detail: "consent record not found",
    };
  }

  const parsed = aggregationConsentRecordSchema.safeParse(resolved);
  if (!parsed.success) {
    return {
      ok: false,
      failureClass: "validation",
      subjectId: rollup.subjectId,
      detail: "resolved consent failed validation",
    };
  }
  const c = parsed.data;
  if (c.consentRecordId !== rollup.consentRecordId) {
    return {
      ok: false,
      failureClass: "validation",
      subjectId: rollup.subjectId,
      detail: "resolved consentRecordId mismatch",
    };
  }
  if (c.subjectId !== rollup.subjectId) {
    return {
      ok: false,
      failureClass: "cross_subject",
      subjectId: rollup.subjectId,
      detail: "consent subjectId must match rollup subjectId",
    };
  }
  if (c.scope !== "aggregation") {
    return {
      ok: false,
      failureClass: "consent_scope",
      subjectId: rollup.subjectId,
      detail: "consent scope must be aggregation",
    };
  }
  if (c.expiresAt !== undefined) {
    const now = options.nowIso ?? new Date().toISOString();
    if (c.expiresAt < now) {
      return {
        ok: false,
        failureClass: "consent_expired",
        subjectId: rollup.subjectId,
        detail: "consent record expired — batch rejected at export time",
      };
    }
  }
  if (!c.active) {
    return {
      ok: false,
      failureClass: "consent_revoked",
      subjectId: rollup.subjectId,
      detail: "consent revoked — batch rejected at ingest/export time",
    };
  }
  if (!c.optedIn) {
    return {
      ok: false,
      failureClass: "consent_denied",
      subjectId: rollup.subjectId,
      detail: "aggregation export requires optedIn === true",
    };
  }

  return {
    ok: true,
    subjectId: rollup.subjectId,
    consentRecordId: rollup.consentRecordId,
  };
}

/**
 * Consent gate that throws typed AggregationConsentError on consent failures.
 * Non-consent validation failures raise a named AggregationContractError.
 */
export function assertAggregationExportConsentOrThrow(
  rollup: FrictionAggregationRollup,
  resolveConsent: (
    consentRecordId: string,
  ) => AggregationConsentRecord | null | undefined,
  options: { nowIso?: string | undefined; deviceId?: string | undefined } = {},
): { subjectId: string; consentRecordId: string } {
  const gate = assertAggregationExportConsent(
    rollup,
    resolveConsent,
    options.nowIso !== undefined ? { nowIso: options.nowIso } : {},
  );
  if (!gate.ok) {
    raiseAggregationConsentError({
      failureClass: gate.failureClass,
      detail: gate.detail,
      subjectId: gate.subjectId,
      consentRecordId: rollup.consentRecordId,
      deviceId: options.deviceId ?? rollup.deviceId,
    });
  }
  return gate;
}

export function parseFrictionAggregationRollup(
  input: unknown,
): ParseFrictionAggregationResult {
  if (input !== null && typeof input === "object") {
    const record = input as Record<string, unknown>;
    for (const key of FORBIDDEN_CONTENT_KEYS) {
      if (key in record) {
        return {
          ok: false,
          failureClass: "keystroke_forbidden",
          subjectId:
            typeof record.subjectId === "string" ? record.subjectId : null,
          detail: `forbidden content key '${key}'`,
          issuePath: key,
        };
      }
    }
  }

  const parsed = frictionAggregationRollupSchema.safeParse(input);
  if (!parsed.success) {
    const first = parsed.error.issues[0];
    const issuePath = first
      ? first.path.map(String).join(".") || "(root)"
      : "(root)";
    const missingConsent =
      issuePath === "consentRecordId" ||
      (first?.message ?? "").includes("consentRecordId");
    return {
      ok: false,
      failureClass: missingConsent ? "consent_missing" : "validation",
      subjectId:
        input !== null &&
        typeof input === "object" &&
        typeof (input as { subjectId?: unknown }).subjectId === "string"
          ? (input as { subjectId: string }).subjectId
          : null,
      detail: first?.message ?? "friction aggregation rollup validation failed",
      issuePath,
    };
  }

  return {
    ok: true,
    record: parsed.data,
    subjectId: parsed.data.subjectId,
    deviceId: parsed.data.deviceId,
  };
}

export type AggregationWriteTelemetryEvent = {
  event: "telemetry.aggregation.write";
  outcome: "queued" | "ok" | "rejected";
  subjectId: string;
  deviceId?: string;
  failureClass?: string;
};

/**
 * Schedule an async rollup persist — returns immediately so the turn hot-path
 * is never blocked waiting on durable I/O.
 */
export function enqueueAggregationWrite(
  record: FrictionAggregationRollup,
  writer: (record: FrictionAggregationRollup) => void | Promise<void>,
  options: {
    onTelemetry?: (event: AggregationWriteTelemetryEvent) => void;
  } = {},
): { queued: true; subjectId: string } {
  const subjectId = record.subjectId;
  options.onTelemetry?.({
    event: "telemetry.aggregation.write",
    outcome: "queued",
    subjectId,
    deviceId: record.deviceId,
  });

  void Promise.resolve()
    .then(() => writer(record))
    .then(() => {
      options.onTelemetry?.({
        event: "telemetry.aggregation.write",
        outcome: "ok",
        subjectId,
        deviceId: record.deviceId,
      });
    })
    .catch((err: unknown) => {
      options.onTelemetry?.({
        event: "telemetry.aggregation.write",
        outcome: "rejected",
        subjectId,
        deviceId: record.deviceId,
        failureClass:
          err instanceof Error ? err.name.slice(0, 64) : "write_failed",
      });
    });

  return { queued: true, subjectId };
}

/**
 * Canonical JSON Schema document for FrictionAggregationRollup (draft-07).
 * Used by the package schema exporter and round-trip tests.
 */
export function toFrictionAggregationJsonSchema(
  protocolVersion: string,
): Record<string, unknown> {
  const raw = z.toJSONSchema(frictionAggregationRollupSchema, {
    target: "draft-07",
    io: "input",
    reused: "inline",
    cycles: "ref",
  });
  const MAX_SAFE = 9007199254740991;
  const stripZodNoise = (node: unknown): unknown => {
    if (Array.isArray(node)) return node.map(stripZodNoise);
    if (!node || typeof node !== "object") return node;
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(node as Record<string, unknown>)) {
      if (k === "maximum" && v === MAX_SAFE) continue;
      if (k === "propertyNames") continue;
      if (k === "additionalProperties" && v === false) continue;
      out[k] = stripZodNoise(v);
    }
    return out;
  };
  return {
    ...(stripZodNoise(raw) as Record<string, unknown>),
    title: "FrictionAggregationRollup",
    "x-protocol-version": protocolVersion,
    "x-aggregation-schema-version": FRICTION_AGGREGATION_SCHEMA_VERSION,
  };
}
