/**
 * @moolam/runtime-harness — Runtime harness core.
 *
 * Streaming turn host for A P6 harness frames. Later slices add incremental
 * parsing, sandbox correction, and abort. Wire contracts are owned by
 * `@moolam/sync-protocol` (A P6); this package consumes them.
 */

export {
  A_P6_HARNESS_FRAME_SCHEMA_PATH,
  STREAMING_TURN_MAX_FRAMES,
  STREAMING_TURN_PROTOCOL_VERSION,
  STREAMING_TURN_SSE_HEARTBEAT_SECONDS_DEFAULT,
  STREAM_RESUME_GAP_CODE,
  StreamingTurnHost,
  buildSequenceGapFrame,
  parseLastEventId,
  resolveStreamResume,
  type AttachTurnMeterAccepted,
  type AttachTurnMeterRejected,
  type AttachTurnMeterResult,
  type FlushMeterAccepted,
  type FlushMeterFailureClass,
  type FlushMeterReconcileAccepted,
  type FlushMeterReconcileRejected,
  type FlushMeterReconcileResult,
  type FlushMeterRejected,
  type FlushMeterResult,
  type GateBudgetBeforeModelResult,
  type GateBudgetBeforeModelUngated,
  type StreamingTurnBudgetGateTelemetryEvent,
  type StreamingTurnRehydrateTelemetryEvent,
  type LastEventIdParseAccepted,
  type LastEventIdParseRejected,
  type LastEventIdParseResult,
  type ResolveStreamResumeOptions,
  type StreamResumeFailureClass,
  type StreamResumeFresh,
  type StreamResumeGap,
  type StreamResumeReject,
  type StreamResumeReplay,
  type StreamResumeResult,
  type StreamingTurnEmitTelemetryEvent,
  type StreamingTurnFailureClass,
  type StreamingTurnHostOptions,
  type StreamingTurnMeterEmitTelemetryEvent,
  type StreamingTurnResumeTelemetryEvent,
  type StreamingTurnTelemetryEvent,
  type StreamingTurnValidateAccepted,
  type StreamingTurnValidateRejected,
  type StreamingTurnValidateResult,
} from "./streaming_turn.js";

export {
  BUDGET_ADVISORY_EXCEEDED,
  BUDGET_ADVISORY_WARNING,
  BUDGET_DECISIONS,
  BUDGET_IDEM_KEY_LIMIT,
  BUDGET_RESERVATION_LIMIT,
  BUDGET_SUBJECT_LIMIT,
  BUDGET_WARNING_THRESHOLD_DEFAULT,
  BudgetManager,
  HARNESS_ERROR_BUDGET_EXCEEDED,
  HARNESS_ERROR_BUDGET_THROTTLE,
  isBudgetDecision,
  runBudgetPreTurnGate,
  type BudgetAdvisory,
  type BudgetAdvisoryCode,
  type BudgetDecision,
  type BudgetExceededHandler,
  type BudgetHarnessErrorSpec,
  type BudgetHook,
  type BudgetLedgerExport,
  type BudgetManagerFailureClass,
  type BudgetManagerOptions,
  type BudgetManagerTelemetryEvent,
  type BudgetMeterTick,
  type BudgetPreTurnGateBlocked,
  type BudgetPreTurnGateFailed,
  type BudgetPreTurnGateProceed,
  type BudgetPreTurnGateResult,
  type BudgetScope,
  type BudgetSnapshot,
  type BudgetSpendChannels,
  type BudgetWarningHandler,
  type SetBudgetInput,
} from "./budget.js";

export {
  COMPACTION_RETENTION_FIXTURE_RELPATH,
  COMPACTION_SECTION_ITEM_LIMIT,
  COMPACTION_SUMMARY_MARKERS,
  COMPACTION_SUMMARY_TOKEN_LIMIT_DEFAULT,
  applyCompactionTrigger,
  canonicalizeCompactionRetentionExpectationJson,
  compileStructuredSummary,
  extractCompactionSections,
  renderCompactionSummaryTemplate,
  replayCompactionRetentionCase,
  type ApplyCompactionTriggerAccepted,
  type ApplyCompactionTriggerDeferred,
  type ApplyCompactionTriggerOptions,
  type ApplyCompactionTriggerRejected,
  type ApplyCompactionTriggerResult,
  type CompactionContextSlice,
  type CompactionDurableState,
  type CompactionExtractedSections,
  type CompactionFailureClass,
  type CompactionKnowledgeItem,
  type CompactionMemoryItem,
  type CompactionTelemetryEvent,
  type CompileStructuredSummaryAccepted,
  type CompileStructuredSummaryDeferred,
  type CompileStructuredSummaryOptions,
  type CompileStructuredSummaryRejected,
  type CompileStructuredSummaryResult,
  type GoldenCompactionMessage,
  type GoldenCompactionRetentionAccepted,
  type GoldenCompactionRetentionCase,
  type GoldenCompactionRetentionCorpus,
  type GoldenCompactionRetentionRejected,
  type GoldenCompactionRetentionResult,
} from "./compaction.js";

export {
  SESSION_ADVISORY_CLEAN_SESSION,
  SESSION_CORRECTION_REF_LIMIT,
  SESSION_DAY_MS,
  SESSION_DURABLE_PROTOCOL_VERSION,
  SESSION_DURABLE_SECTION_CHAR_LIMIT,
  SESSION_STORE_BACKEND_ENV,
  SESSION_STORE_ENTRY_LIMIT,
  SESSION_STORE_PATH_ENV,
  FileSessionDurableStore,
  InMemorySessionDurableStore,
  canonicalizeSessionDurableStateJson,
  computeSessionDaysSinceWrite,
  createEmptySessionDurableState,
  parseSessionDurableState,
  rehydrateSessionForTurn,
  resetSessionDurableStoreSelectionLogForTests,
  runSessionRehydrationDaysGapScenario,
  selectSessionDurableStore,
  type RehydrateSessionAccepted,
  type RehydrateSessionOptions,
  type RehydrateSessionRejected,
  type RehydrateSessionResult,
  type RehydratedTurnSeed,
  type SessionCorrectionRef,
  type SessionDurableAdvisoryCode,
  type SessionDurableBackendName,
  type SessionDurableFailureClass,
  type SessionDurableState,
  type SessionDurableStore,
  type SessionDurableTelemetryEvent,
  type SessionProfileSnapshot,
  type SessionStoreDeleteAccepted,
  type SessionStoreDeleteResult,
  type SessionStoreGetCorruptedAdvisory,
  type SessionStoreGetEmpty,
  type SessionStoreGetFound,
  type SessionStoreGetNotFound,
  type SessionStoreGetRejected,
  type SessionStoreGetResult,
  type SessionStoreOpOptions,
  type SessionStorePutAccepted,
  type SessionStorePutRejected,
  type SessionStorePutResult,
  type SelectSessionDurableStoreOptions,
} from "./session_store.js";

export {
  A_P6_DEGRADATION_REGISTRY_FIXTURE_RELPATH,
  DEGRADATION_BEHAVIORS,
  DEGRADATION_BEHAVIOR_CASE_LIMIT,
  DEGRADATION_BEHAVIOR_FIXTURE_RELPATH,
  DEGRADATION_BEHAVIOR_SIGNAL_CODES,
  DEGRADATION_DEPENDENCY_NAME_LIMIT,
  DEGRADATION_DEPENDENCY_REGISTER_LIMIT,
  DEGRADATION_MODES,
  DEGRADATION_OPERATIONS,
  DEGRADATION_SURFACES,
  DEGRADATION_WIRE_DEPENDENCIES,
  DEFAULT_DEGRADATION_REGISTRY,
  RuntimeDegradationRegistry,
  assertBehaviorCorpusCoverage,
  degradationBehaviorToMode,
  degradationModeToBehavior,
  invokeModelDependency,
  invokeSyncDependency,
  invokeToolDependency,
  invokeWithDegradation,
  isDegradationBehavior,
  loadDegradationRegistry,
  parseDegradationBehaviorCase,
  runDegradationBehaviorCase,
  type DegradationAdvisoryOutcome,
  type DegradationAdvisorySignal,
  type DegradationBehavior,
  type DegradationBehaviorCase,
  type DegradationBehaviorSpec,
  type DegradationMode,
  type DegradationOperation,
  type DegradationRegistryDocument,
  type DegradationRegistryFailureClass,
  type DegradationRegistryTelemetryEvent,
  type DegradationSurface,
  type DegradationWireDependency,
  type InvokeWithDegradationOptions,
  type InvokeWithDegradationResult,
  type LoadDegradationRegistryAccepted,
  type LoadDegradationRegistryOptions,
  type LoadDegradationRegistryRejected,
  type LoadDegradationRegistryResult,
  type RegisterDegradationAccepted,
  type RegisterDegradationRejected,
  type RegisterDegradationResult,
  type ResolveDegradationAccepted,
  type ResolveDegradationRejected,
  type ResolveDegradationResult,
  type RunDegradationBehaviorCaseAccepted,
  type RunDegradationBehaviorCaseRejected,
  type RunDegradationBehaviorCaseResult,
} from "./degradation_registry.js";

export {
  CONTEXT_ADVISORY_MISSING_WINDOW,
  CONTEXT_BUDGET_THRESHOLD_FIXTURE_RELPATH,
  CONTEXT_CHARS_PER_TOKEN_ESTIMATE,
  CONTEXT_COMPACTION_THRESHOLD_DEFAULT,
  CONTEXT_MEMORY_LIMIT,
  CONTEXT_MESSAGE_LIMIT,
  CONTEXT_RETRIEVAL_LIMIT,
  CONTEXT_SECTION_CHAR_LIMIT,
  CONTEXT_WINDOW_CONSERVATIVE_DEFAULT,
  ContextBudgetManager,
  buildScoredTruncateCandidates,
  canonicalizeContextBudgetExpectationJson,
  estimateContextTextTokens,
  loadContextWindowFromModelCard,
  replayContextBudgetThresholdCase,
  truncateScoredCandidates,
  type ContextBudgetAdvisoryCode,
  type ContextBudgetFailureClass,
  type ContextBudgetManagerOptions,
  type ContextBudgetMeasureAccepted,
  type ContextBudgetMeasureInput,
  type ContextBudgetMeasureRejected,
  type ContextBudgetMeasureResult,
  type ContextBudgetSnapshot,
  type ContextBudgetTelemetryEvent,
  type ContextMemoryItem,
  type ContextModelCard,
  type ContextRetrievalPassage,
  type GoldenContextBudgetAccepted,
  type GoldenContextBudgetCase,
  type GoldenContextBudgetCorpus,
  type GoldenContextBudgetRejected,
  type GoldenContextBudgetResult,
  type TruncateRecallKnowledgeAccepted,
  type TruncateRecallKnowledgeInput,
  type TruncateRecallKnowledgeRejected,
  type TruncateRecallKnowledgeResult,
} from "./context_budget.js";

export {
  PROMPT_ASSEMBLY_DETERMINISM_FIXTURE_RELPATH,
  PROMPT_BINDINGS_FIELD_KEY_LIMIT,
  PROMPT_BINDINGS_HASH_ALGORITHM,
  PROMPT_BLOCK_MARKERS,
  PROMPT_DYNAMIC_MEMORY_LIMIT,
  PROMPT_DYNAMIC_PASSAGE_LIMIT,
  PROMPT_SECTION_CHAR_LIMIT,
  PROMPT_STATIC_CACHE_ENTRY_LIMIT_DEFAULT,
  PROMPT_STATIC_CACHE_ENTRY_LIMIT_MAX,
  PROMPT_STATIC_CACHE_TTL_MS_DEFAULT,
  PROMPT_STATIC_CHARS_PER_TOKEN_ESTIMATE,
  InMemoryStaticPromptCache,
  assembleDynamic,
  assemblePrompt,
  assembleStatic,
  canonicalizeBindingsStateJson,
  canonicalizeProfileMetaJson,
  canonicalizePromptAssemblyExpectationJson,
  estimateStaticBlockTokens,
  hashBindingsState,
  meterCachedStaticAssembly,
  replayPromptAssemblyDeterminismCase,
  splitPromptBlocks,
  type AssembleDynamicAccepted,
  type AssembleDynamicResult,
  type AssemblePromptAccepted,
  type AssemblePromptResult,
  type AssembleRejected,
  type AssembleStaticAccepted,
  type AssembleStaticResult,
  type AssembledPrompt,
  type AssembledPromptBlock,
  type GoldenPromptAssemblyAccepted,
  type GoldenPromptAssemblyCase,
  type GoldenPromptAssemblyCorpus,
  type GoldenPromptAssemblyRejected,
  type GoldenPromptAssemblyResult,
  type HashBindingsAccepted,
  type HashBindingsResult,
  type InMemoryStaticPromptCacheOptions,
  type MeterCachedStaticAssemblyAccepted,
  type MeterCachedStaticAssemblyRejected,
  type MeterCachedStaticAssemblyResult,
  type PromptAssemblerOptions,
  type PromptBindingsState,
  type PromptCacheFailureClass,
  type PromptCacheMissMarker,
  type PromptCacheTelemetryEvent,
  type PromptMemoryItem,
  type PromptPassageItem,
  type PromptProfile,
  type PromptProtocol,
  type PromptTurnContext,
  type StaticPromptCacheEntry,
  type StaticPromptCacheGetOrAssembleAccepted,
  type StaticPromptCacheGetOrAssembleResult,
  type StaticPromptCacheLookupHit,
  type StaticPromptCacheLookupMiss,
  type StaticPromptCacheLookupRejected,
  type StaticPromptCacheLookupResult,
  type StaticPromptCacheStats,
  type StaticPromptCacheStoreAccepted,
  type StaticPromptCacheStoreResult,
} from "./prompt_cache.js";

export {
  METERING_RECONCILE_FIXTURE_RELPATH,
  METER_GOLDEN_TOKEN_TOLERANCE,
  TURN_METER_IDEM_KEY_LIMIT,
  TURN_METER_SEGMENT_LIMIT,
  TurnMeter,
  assertTurnMeterSubjectScope,
  buildHarnessMeterRuntimeEvent,
  canonicalizeMeterEventsJson,
  publishHarnessMeterSpine,
  reconcileMeterTokensWithinTolerance,
  replayGoldenMeterReconcileCase,
  type GoldenMeterReconcileAccepted,
  type GoldenMeterReconcileCase,
  type GoldenMeterReconcileCorpus,
  type GoldenMeterReconcileRejected,
  type GoldenMeterReconcileResult,
  type MeterSpinePublisher,
  type MeterTokenTolerance,
  type RecordTurnTokensInput,
  type RecordTurnTokensResult,
  type SetProviderUsageResult,
  type TurnMeterFailureClass,
  type TurnMeterFlushAccepted,
  type TurnMeterFlushRejected,
  type TurnMeterFlushResult,
  type TurnMeterOptions,
  type TurnMeterTelemetryEvent,
} from "./metering.js";

export {
  STREAM_BUFFER_RESYNC_ADVISORY,
  STREAM_FRAME_BUFFER_RETENTION_DEFAULT,
  STREAM_FRAME_BUFFER_RETENTION_MAX,
  InMemoryStreamFrameBuffer,
  type InMemoryStreamFrameBufferOptions,
  type StreamBufferAppendAccepted,
  type StreamBufferAppendRejected,
  type StreamBufferAppendResult,
  type StreamBufferFailureClass,
  type StreamBufferReplayAccepted,
  type StreamBufferReplayRejected,
  type StreamBufferReplayResult,
  type StreamBufferTelemetryEvent,
  type StreamFrameBuffer,
} from "./stream_frame_buffer.js";

export {
  PARSER_CARRY_MAX,
  PARSER_DECLARED_TAGS,
  PARSER_MODES,
  PARSER_MODE_TRANSITIONS,
  PARSER_TOOL_BUFFER_MAX,
  ToolCallParser,
  isTagFragmentPrefix,
  parseChunks,
  tagFragmentHoldStart,
  type ParseEvent,
  type ParserDeclaredTagName,
  type ParserFailureClass,
  type ParserMode,
  type ParserModeTransition,
  type ToolCallParserOptions,
  type ToolCallParserTelemetryEvent,
} from "./tool_call_parser.js";

export {
  A_P6_GOLDEN_TURNS_FIXTURE_RELPATH,
  canonicalGoldenTurnBytes,
  listImportedGoldenTurnFiles,
  loadGoldenTurnCorpus,
  resolveGoldenTurnFixtureDir,
  resolveUpstreamGoldenTurnDir,
  type GoldenTurnCorpusLoadRejected,
  type GoldenTurnCorpusLoadResult,
  type GoldenTurnCorpusLoaded,
  type GoldenTurnLoadFailureClass,
  type GoldenTurnLoadTelemetryEvent,
  type LoadGoldenTurnCorpusOptions,
} from "./golden_turn_loader.js";

export {
  canonicalizeFramesJson,
  replayGoldenTurn,
  replayGoldenTurnCorpus,
  type GoldenReplayAccepted,
  type GoldenReplayFailureClass,
  type GoldenReplayRejected,
  type GoldenReplayResult,
  type GoldenReplayTelemetryEvent,
  type ReplayGoldenTurnOptions,
} from "./golden_turn_replay.js";

export {
  createDefaultGymToolRegistry,
  runProductionTurnLoop,
  type ProductionTurnLoopAccepted,
  type ProductionTurnLoopFailureClass,
  type ProductionTurnLoopOptions,
  type ProductionTurnLoopRejected,
  type ProductionTurnLoopResult,
  type ProductionTurnLoopTelemetry,
} from "./production_turn_loop.js";

export { unifiedDiff, type UnifiedDiffOptions } from "./unified_diff.js";

export {
  CHUNK_FUZZ_DEFAULT_SEED,
  CHUNK_FUZZ_MAX_CUTS,
  CHUNK_FUZZ_MAX_EXHAUSTIVE_LEN,
  CHUNK_FUZZ_MAX_RANDOM_TRIALS,
  SEED_DRIFT_MARKER,
  canonicalizeEventsJson,
  createSeededRng,
  parseableGoldenStream,
  runChunkBoundaryFuzz,
  runChunkBoundaryFuzzCorpus,
  splitStreamAtCuts,
  summarizeParseEvents,
  type ChunkFuzzAccepted,
  type ChunkFuzzFailureClass,
  type ChunkFuzzRejected,
  type ChunkFuzzResult,
  type ChunkFuzzTelemetryEvent,
  type RunChunkBoundaryFuzzOptions,
} from "./chunk_boundary_fuzz.js";

export {
  SANDBOX_DEFAULT_DEADLINE_MS,
  SANDBOX_INVOKE_LOG_LIMIT,
  SANDBOX_MAX_BYTES_DEFAULT,
  SANDBOX_REGISTRY_LIMIT,
  SANDBOX_RESULT_SCHEMA_OBLIGATION,
  SANDBOX_SCHEMA_ISSUE_LIMIT,
  InProcessFakeToolRegistry,
  createSandboxSeam,
  invokeSandboxAndMap,
  mapSandboxResultToToolResponse,
  mapSandboxResultToToolStatus,
  validateToolResultSchema,
  type CreateSandboxSeamOptions,
  type FakeToolEffect,
  type InProcessFakeToolSpec,
  type MapSandboxResultOptions,
  type SandboxInvokeAccepted,
  type SandboxInvokeRejected,
  type SandboxInvokeResult,
  type SandboxInvokeTrace,
  type SandboxInvokeTracePhase,
  type SandboxResultJsonSchema,
  type SandboxResultValidation,
  type SandboxSchemaIssue,
  type SandboxSeam,
  type SandboxSeamContext,
  type SandboxSeamFailureClass,
  type SandboxSeamTelemetryEvent,
  type SandboxToolResponse,
} from "./sandbox_seam.js";

export {
  ABORT_AUDIT_RECORD_LIMIT,
  ABORT_JOURNAL_LIMIT,
  ABORT_LOCK_LIMIT,
  ABORT_REASON_MANUAL,
  ABORT_REGISTRY_LIMIT,
  ACCEPT_VS_ABORT_ACTIONS,
  AGENT_MANUAL_ABORT_AUDIT_EVENT,
  AbortPipeline,
  EffectJournal,
  IdempotencyLockTable,
  InMemoryAbortAuditSink,
  InProcessFakeDurableEffects,
  TurnAbortHandle,
  waitForAbortSignal,
  type AbortAuditSink,
  type AbortPipelineFailureClass,
  type AbortPipelineOptions,
  type AbortPipelineTelemetryEvent,
  type AbortTurnAccepted,
  type AbortTurnOptions,
  type AbortTurnRejected,
  type AbortTurnResult,
  type AcceptVsAbortAction,
  type AgentManualAbortAuditRecord,
  type AppendEffectInput,
  type EffectCompensateFn,
  type EffectJournalEntry,
  type EffectJournalStatus,
  type MarkTurnCompletedOptions,
  type MarkTurnCompletedResult,
  type RegisterTurnAccepted,
  type RegisterTurnOptions,
  type RegisterTurnRejected,
  type RegisterTurnResult,
  type TurnAbortStatus,
} from "./abort_pipeline.js";

export {
  CORRECTION_CAP_ESCALATION_FIXTURE_RELPATH,
  CORRECTION_EXHAUSTED_CODE,
  CORRECTION_RULE_ENVELOPE,
  CORRECTION_RULE_POLICY,
  CORRECTION_RULE_RESULT_SCHEMA,
  CORRECTION_RULE_SANDBOX,
  CorrectionDepthTracker,
  MAX_CORRECTION_TURNS,
  PROCESS_REWARD_ABS_CAP,
  PROCESS_REWARD_CORRECTION_FIXTURES_RELPATH,
  StreamingTurnCorrectionLoop,
  buildCorrectionCycleFeatures,
  formatCorrectionSystemError,
  resolveMaxCorrectionTurns,
  snapshotCorrectionCycleFeatures,
  type CorrectionCycleAccepted,
  type CorrectionCycleExhausted,
  type CorrectionCycleFeatures,
  type CorrectionCycleRejected,
  type CorrectionCycleResult,
  type CorrectionDepthTrackerOptions,
  type CorrectionFailureInput,
  type CorrectionFailureKind,
  type CorrectionHarnessError,
  type CorrectionLoopConfig,
  type CorrectionLoopTelemetryEvent,
  type CorrectionModelResumeFn,
  type CorrectionModelResumeResult,
  type CorrectionRecordAccepted,
  type CorrectionRecordRejected,
  type CorrectionRecordResult,
  type CorrectionSystemError,
  type StreamingTurnCorrectionLoopOptions,
} from "./correction_loop.js";

export {
  ApprovalSurface,
  ApprovalTimeoutError,
  type AbortSurfaceAction,
  type ApprovalCompleteResult,
  type ApprovalDecideResult,
  type ApprovalSurfaceContext,
  type ApprovalSurfaceDecision,
  type ApprovalSurfaceOptions,
  type ApprovalSurfaceRiskClass,
  type ApprovalSurfaceTelemetryEvent,
  type ApprovalTurnBeginResult,
  type DiscardTurnResult,
  type HostApprovalCallback,
  type MapAbortToDiscardResult,
} from "./approval_surface.js";

export {
  FORBIDDEN_REMEDIATION_SURFACES,
  REMEDIATION_ACTION_KINDS,
  REMEDIATION_CONTROL_SURFACES,
  REMEDIATION_CORRECTION_CAP_DEFAULT,
  REMEDIATION_CORRECTION_CAP_MAX,
  REMEDIATION_CORRECTION_CAP_MIN,
  REMEDIATION_DEGRADATION_BEHAVIORS,
  REMEDIATION_DEGRADATION_DEPENDENCIES,
  REMEDIATION_FAILURE_CLASSES,
  REMEDIATION_INEFFECTIVE_ATTEMPT_LIMIT,
  REMEDIATION_POLICY_FLAG,
  REMEDIATION_POLICY_ROW_LIMIT,
  REMEDIATION_POLICY_SCHEMA_VERSION,
  REMEDIATION_RETRY_BUDGET_MAX,
  REMEDIATION_RETRY_BUDGET_MIN,
  REMEDIATION_ROUTING_FALLBACKS,
  RemediationPolicyContractError,
  buildRemediationPolicyDraft,
  createRemediationPolicyCatalog,
  isRemediationAction,
  nextIneffectiveAttemptPolicy,
  parseRemediationAction,
  parseRemediationPolicy,
  selectRemediationPolicy,
  type AdjustRetryBudgetAction,
  type ForbiddenRemediationSurface,
  type RemediationAction,
  type RemediationActionKind,
  type RemediationControlSurface,
  type RemediationDegradationBehavior,
  type RemediationDegradationDependency,
  type RemediationFailureClass,
  type RemediationLocality,
  type RemediationPolicyCatalog,
  type RemediationPolicyDocument,
  type RemediationPolicyFailureClass,
  type RemediationPolicyTelemetryEvent,
  type RemediationRoutingFallback,
  type SetCorrectionLoopCapAction,
  type SetRoutingFallbackAction,
  type SwitchDegradationModeAction,
} from "./self_healing/remediation_policy.js";

export {
  REMEDIATION_EXECUTION_RECEIPT_LIMIT,
  REMEDIATION_EXECUTOR_FLAG,
  REMEDIATION_EXECUTOR_SCHEMA_VERSION,
  RemediationExecutorContractError,
  createInMemoryRemediationSurfaces,
  createRemediationExecutor,
  type ExecuteRemediationInput,
  type InMemoryRemediationSurfaceState,
  type RemediationControlSurfacePorts,
  type RemediationExecuteResult,
  type RemediationExecutor,
  type RemediationExecutorFailureClass,
  type RemediationExecutorTelemetryEvent,
  type ReportRemediationOutcomeInput,
} from "./self_healing/remediation_executor.js";

export {
  REMEDIATION_FIXTURES_RELPATH,
  REMEDIATION_FIXTURE_SCHEMA_VERSION,
  proveRemediationFixture,
  proveRemediationFixturesCi,
  type RemediationFixtureDocument,
  type RemediationFixtureExpectation,
  type RemediationFixtureKind,
  type RemediationFixturePolicySeed,
  type RemediationFixtureProbe,
  type RemediationFixtureTelemetryEvent,
} from "./self_healing/remediation_prove.js";

/** Re-export A P6 frame surface so hosts import one package for turn streaming. */
export {
  HARNESS_FRAME_TYPES,
  assertMonotonicSequence,
  harnessFrameSchema,
  parseHarnessFrame,
  type HarnessErrorFrame,
  type HarnessFrame,
  type HarnessFrameType,
  type SessionStartFrame,
  type TurnCompleteFrame,
} from "@moolam/sync-protocol";
