/**
 * sutra-bindings-vision — local VLM behind VisionInterface.
 */

export {
  DEFAULT_MAX_INPUT_BYTES,
  LOCAL_VLM_ENGINE,
  SUPPORTED_VISION_MIME_TYPES,
  VISION_PACKAGE_ROOT,
  VLM_STREAM_LIMIT,
  LocalVlmBinding,
  LocalVlmError,
  VisionFormatError,
  VisionInputTooLargeError,
  VisionSchemaError,
  assertDecodableVisualInput,
  createInProcessLocalVlmBackend,
  createLocalVlmVisionHarnessFactory,
  loadLocalVlm,
  type CreateLocalVlmVisionHarnessOptions,
  type LoadLocalVlmOptions,
  type LocalVlmAnalyzeNativeParams,
  type LocalVlmAnalyzeNativeResult,
  type LocalVlmNativeBackend,
  type LocalVlmNativeHandle,
  type LocalVlmTelemetryEvent,
  type LocalVlmTelemetryOp,
  type VisionFailureClass,
} from "./vlm_binding.js";

export {
  CK06_FIXTURES_DIR,
  DEFAULT_CK06_FIXTURE_CATALOG,
  listCk06FixtureIds,
  loadAllCk06Fixtures,
  loadCk06Fixture,
  loadCk06FixtureCatalog,
  runAllCk06Fixtures,
  runCk06Fixture,
  type Ck06Fixture,
  type Ck06FixtureCatalog,
  type Ck06FixtureExpect,
  type Ck06FixtureKind,
  type Ck06FixtureMeta,
  type Ck06FixtureRunResult,
} from "./vision_fixtures.js";

export {
  DEFAULT_OFFLINE_VISION_FIXTURE_ID,
  OFFLINE_EDGE_GOLDEN_RELPATH,
  createEdgeBindingsWithVision,
  proveOfflineEdgeVisionBinding,
  type OfflineEdgeVisionTelemetry,
  type ProveOfflineEdgeVisionOptions,
  type ProveOfflineEdgeVisionResult,
} from "./edge_vlm_harness.js";

export {
  CBSE_WORKSHEET_SCHEMA_ID,
  CBSE_WORKSHEET_SCHEMA_PATH,
  CBSE_WORKSHEET_SCHEMA_VERSION,
  DEFAULT_DOCUMENT_FIXTURE_CATALOG,
  DEFAULT_PRESCRIPTION_EXTRACT_INSTRUCTION,
  DOCUMENT_FIXTURES_DIR,
  DOCUMENT_SCHEMAS_DIR,
  DOCUMENT_SCHEMA_SCAN_LIMIT,
  PRESCRIPTION_SKETCH_SCHEMA_ID,
  PRESCRIPTION_SKETCH_SCHEMA_PATH,
  PRESCRIPTION_SKETCH_SCHEMA_VERSION,
  TEXTBOOK_PAGE_SCHEMA_ID,
  TEXTBOOK_PAGE_SCHEMA_PATH,
  TEXTBOOK_PAGE_SCHEMA_VERSION,
  assertSingleDocumentImage,
  extractPrescriptionSketch,
  listDocumentExtractionProfiles,
  loadAllDocumentFixtures,
  loadDocumentFixture,
  loadDocumentFixtureCatalog,
  loadDocumentResponseSchema,
  proveDocumentSchemaFixture,
  provePrescriptionSketchExtraction,
  resolveDocumentSchemaPath,
  validateDocumentExtractionAnswer,
  type DocumentExtractionProfileId,
  type DocumentFixture,
  type DocumentFixtureCatalog,
  type DocumentFixtureMeta,
  type DocumentSchemaMeta,
  type DocumentTelemetryEvent,
  type DocumentValidationFail,
  type DocumentValidationOk,
  type PrescriptionSketchExtractOk,
  type PrescriptionSketchExtractResult,
} from "./document_understanding.js";

export {
  DEFAULT_DOCUMENT_GOLDEN_CATALOG,
  DEFAULT_DOCUMENT_GOLDEN_RUBRIC,
  DOCUMENT_GOLDEN_DIR,
  DOCUMENT_GOLDEN_REPORT_SCHEMA_VERSION,
  assertNoPiiInText,
  loadAllDocumentGoldenFixtures,
  loadDocumentGoldenCatalog,
  loadDocumentGoldenFixture,
  loadDocumentGoldenRubric,
  proveDocumentGoldenGate,
  runDocumentGoldenCli,
  runDocumentGoldenSuite,
  scoreDocumentGoldenAnswer,
  writeDocumentGoldenReport,
  type DocumentGoldenCatalog,
  type DocumentGoldenDomain,
  type DocumentGoldenFixture,
  type DocumentGoldenMeta,
  type DocumentGoldenRunReport,
  type DocumentGoldenRubric,
  type DocumentGoldenScore,
  type DocumentGoldenTelemetry,
  type RubricDimensionScore,
} from "./document_golden.js";

