/**
 * sutra-bindings-knowledge — versioned knowledge-pack format + pack loader.
 */

export {
  KNOWLEDGE_PACKAGE_ROOT,
  PACK_CITATION_LOCATOR_MAX,
  PACK_LANGUAGES_LIMIT,
  PACK_PASSAGE_CONTENT_MAX_CHARS,
  PACK_SHARD_PASSAGE_LIMIT,
  PACK_SHARDS_LIMIT,
  PACK_SOURCES_LIMIT,
  PACK_VECTOR_DIM_MAX,
  PACK_VECTOR_DIM_MIN,
  PACK_VECTOR_DTYPE_BYTES,
  PACK_VECTOR_EMBEDDINGS_RELPATH,
  PACK_VECTOR_ENTRIES_LIMIT,
  PACK_VECTOR_ID_MAP_RELPATH,
  PACK_V1_JSON_SCHEMA_PATH,
  PACK_V1_SCHEMA_VERSION,
  PackFormatError,
  assertCommittedPackV1Schema,
  expectedEmbeddingsByteLength,
  isFullVectorIndexLayer,
  loadContentShardFile,
  loadPackManifestFile,
  packCitationSchema,
  packContentShardSchema,
  packManifestSchema,
  packPassageSchema,
  packSourceSchema,
  packVectorIdMapEntrySchema,
  packVectorIdMapSchema,
  parseContentShard,
  parsePackManifest,
  parsePackStampMs,
  parseVectorIdMap,
  validateShardAgainstManifest,
  validateVectorIndexIntegrity,
  type PackCitation,
  type PackContentShard,
  type PackFailureClass,
  type PackFormatTelemetry,
  type PackManifest,
  type PackParseFail,
  type PackParseOk,
  type PackPassage,
  type PackSource,
  type PackVectorDtype,
  type PackVectorIdMap,
  type PackVectorIdMapEntry,
  type PackVectorIndex,
} from "./pack_format.js";

export {
  parseValidatePackArgv,
  runValidatePackCli,
  validatePack,
  type ParsedValidatePackCli,
  type ValidatePackCliIo,
  type ValidatePackOk,
  type ValidatePackResult,
} from "./pack_validator.js";

export {
  PACK_CORPUS_SCAN_LIMIT,
  PACK_RETRIEVE_LIMIT_DEFAULT,
  PACK_RETRIEVE_LIMIT_MAX,
  PackKnowledgeConnector,
  PackLoadError,
  TEACHER_CBSE_SLICE_PACK_ID,
  TEACHER_CBSE_SLICE_PACK_RELPATH,
  DOCTOR_FORMULARY_SKETCH_PACK_ID,
  DOCTOR_FORMULARY_SKETCH_PACK_RELPATH,
  createPackKnowledgeConnector,
  keywordScore,
  loadTeacherCbseSliceConnector,
  loadDoctorFormularySketchConnector,
  packEmbedText,
  resolveTeacherCbseSlicePackRoot,
  resolveDoctorFormularySketchPackRoot,
  type PackKnowledgeConnectorOptions,
  type PackLoaderTelemetry,
} from "./pack_loader.js";

export {
  DEFAULT_OFFLINE_PACK_RELPATH,
  createPackKnowledgeConformanceHarness,
  proveOfflinePackRetrieve,
  type OfflinePackRetrieveTelemetry,
  type ProveOfflinePackRetrieveOptions,
  type ProveOfflinePackRetrieveResult,
} from "./pack_offline_proof.js";

export {
  assertPackIsDataNotDomainImport,
  proveTeacherPackCognitiveCore,
  type ProveTeacherPackCognitiveCoreOptions,
  type ProveTeacherPackCognitiveCoreResult,
  type TeacherPackWiringTelemetry,
} from "./pack_example_wiring.js";

export {
  PACK_PROVENANCE_SCHEMA_VERSION,
  TEACHER_CBSE_SLICE_OUT_RELPATH,
  TEACHER_CBSE_SLICE_SOURCE_RELPATH,
  DOCTOR_FORMULARY_SKETCH_OUT_RELPATH,
  DOCTOR_FORMULARY_SKETCH_SOURCE_RELPATH,
  FLAGSHIP_PACK_SPECS,
  buildFlagshipPack,
  buildTeacherCbseSlicePack,
  buildDoctorFormularySketchPack,
  checkFlagshipPackFreshness,
  checkTeacherCbseSliceFreshness,
  checkDoctorFormularySketchFreshness,
  fingerprintSourceFiles,
  parseBuildPackArgv,
  parsePackAuthoringMarkdown,
  resolveFlagshipPackSpec,
  resolveRepoRoot,
  runBuildPackCli,
  stableContentHash,
  type BuildFlagshipPackOptions,
  type BuildFlagshipPackResult,
  type BuildTeacherCbseSliceOptions,
  type BuildTeacherCbseSliceResult,
  type CheckPackFreshnessResult,
  type FlagshipPackId,
  type FlagshipPackSpec,
  type PackBuildTelemetry,
  type PackProvenance,
} from "./pack_build.js";

export {
  FLAGSHIP_PACK_IDS,
  FLAGSHIP_PACKS_CI_NOW_MS,
  assertFlagshipPackTreesPresent,
  proveFlagshipPacksCiGate,
  runFlagshipPacksCiGate,
  runFlagshipPacksCiGateCli,
  type FlagshipPackGateRow,
  type FlagshipPacksCiGateOptions,
  type FlagshipPacksCiGateResult,
  type FlagshipPacksCiTelemetry,
  type ProveFlagshipPacksCiResult,
} from "./pack_ci_gate.js";

