/**
 * Published critic calibration path (C3) — held-out set, agreement, promotion gate.
 * Source of truth: packages/learning/src/critics/calibration.ts
 * Sets live under training/eval/calibration_sets/.
 */
export {
  CALIBRATION_SETS_RELPATH,
  CALIBRATION_SET_ENTRY_LIMIT,
  CALIBRATION_SET_ID_LIMIT,
  CALIBRATION_SET_SCHEMA_VERSION,
  CALIBRATION_SLICE_TAG_LIMIT,
  CALIBRATION_AGREEMENT_METRICS,
  CALIBRATION_KNOWN_BAD_RUBRIC_ID,
  CALIBRATION_KNOWN_BAD_RUBRIC_RELPATH,
  CALIBRATION_KNOWN_BAD_RUBRIC_VERSION,
  CALIBRATION_KNOWN_BAD_SCHEMA_VERSION,
  CalibrationContractError,
  assertCalibrationDecontaminatedAgainstBaselines,
  assertCorpusExcludedFromCalibrationSet,
  assertCriticEligibleForTrainingConfig,
  assertCriticHumanAgreementPasses,
  buildAgreementPairs,
  buildTrainingCriticConfigPin,
  calibrationSetEntrySchema,
  calibrationSetManifestSchema,
  calibrationSliceId,
  computeCalibrationContentHash,
  computeCohenKappa,
  computeCriticHumanAgreement,
  createKnownBadCalibrationCritic,
  criticScoreToBinaryLabel,
  exportCalibrationContentHashes,
  humanOutcomeToBinaryLabel,
  listCalibrationSliceIds,
  loadCalibrationSet,
  loadKnownBadCalibrationRubric,
  parseCalibrationSetManifest,
  predictCriticLabelsOnCalibrationSet,
  proveCalibrationPromotionGate,
  runCriticCalibrationPromotionGate,
  stripHumanOutcomeForCalibrationScoring,
  type AgreementMetricResult,
  type AgreementPair,
  type BinaryCalibrationLabel,
  type CalibrationAgreementMetricId,
  type CalibrationFailureClass,
  type CalibrationPromotionVerdict,
  type CalibrationSetEntry,
  type CalibrationSetManifest,
  type CalibrationSliceTags,
  type CalibrationTelemetryEvent,
  type Contingency2x2,
  type CorpusHashCandidate,
  type CriticHumanAgreementReport,
  type CriticPromotionCandidate,
  type KnownBadCalibrationRubric,
  type LoadedCalibrationEntry,
  type LoadedCalibrationSet,
  type SliceAgreementMetrics,
  type TrainingCriticConfigPin,
} from "@moolam/learning";
