/**
 * Published hack fixture suite path (C3) — fixtures, composite ≤0, CI gate.
 * Source of truth: packages/learning/src/critics/hack_fixtures.ts
 * Fixtures: training/critics/fixtures/hack/
 */
export {
  HACK_ATTACK_DOC_LIMIT,
  HACK_ATTACK_PATTERNS,
  HACK_COMPOSITE_LAYER_LIMIT,
  HACK_COMPOSITE_SCHEMA_VERSION,
  HACK_FIXTURES_RELPATH,
  HACK_FIXTURE_ID_LIMIT,
  HACK_FIXTURE_SCHEMA_VERSION,
  HACK_RED_TEAM_FAMILIES,
  HACK_SUITE_CI_SCRIPT,
  CALIBRATION_CI_SCRIPT,
  HACK_SUITE_ENTRY_LIMIT,
  HACK_SUITE_MANIFEST_SCHEMA_VERSION,
  HackFixtureContractError,
  assertHackSuiteAllowsCalibration,
  assertHackSuiteCompositeNonPositive,
  assertHackSuiteRunsBeforeCalibrationInCi,
  assertCriticVersionClearsHackSuite,
  createDefaultHackCompositeStack,
  createLeakyPositiveHackCritic,
  hackFixtureDocumentSchema,
  hackSuiteManifestSchema,
  listHackAttackPatterns,
  loadHackFixtureSuite,
  parseHackFixtureDocument,
  parseHackSuiteManifest,
  proveHackSuiteCriticVersionGate,
  runHackSuiteComposite,
  scoreHackFixtureComposite,
  type CriticVersionHackGateVerdict,
  type HackAttackPattern,
  type HackCompositeFixtureResult,
  type HackCompositeLayerScore,
  type HackCompositeSuiteReport,
  type HackFixtureDocument,
  type HackFixtureFailureClass,
  type HackFixtureTelemetryEvent,
  type HackRedTeamFamily,
  type HackSuiteManifest,
  type LoadedHackFixture,
  type LoadedHackSuite,
} from "@moolam/learning";
