/**
 * sutra-bindings-speech — local Indic speech (whisper.cpp-class STT).
 */

export {
  createInProcessWhisperCppBackend,
  type WhisperCppNativeBackend,
  type WhisperCppNativeHandle,
  type WhisperCppTranscribeNativeParams,
  type WhisperCppTranscribeNativeResult,
} from "./whisper_ffi.js";

export {
  DEFAULT_INDIC_LANGUAGES_MANIFEST,
  DEFAULT_INDIC_UTTERANCE_CATALOG,
  INDIC_FIXTURES_DIR,
  PACKAGE_ROOT,
  SPEECH_SAMPLE_RATE_HZ,
  SPEECH_STREAM_CHUNK_LIMIT,
  WHISPER_CPP_CLASS_ENGINE,
  WhisperCppSpeechBinding,
  WhisperCppSpeechError,
  createWhisperCppSpeechHarnessFactory,
  indicFixtureAsAudioStream,
  listIndicUtteranceIds,
  loadAllIndicUtteranceFixtures,
  loadIndicLanguagesManifest,
  loadIndicUtteranceCatalog,
  loadIndicUtteranceFixture,
  loadWhisperCppSpeech,
  type CreateWhisperCppSpeechHarnessOptions,
  type IndicLanguagesManifest,
  type IndicUtteranceCatalog,
  type IndicUtteranceFixture,
  type IndicUtteranceFixtureMeta,
  type IndicUtteranceKind,
  type LoadWhisperCppSpeechOptions,
  type WhisperCppSttTelemetryEvent,
  type WhisperCppSttTelemetryOp,
} from "./stt_binding.js";

export {
  OFFLINE_EDGE_GOLDEN_RELPATH,
  createEdgeBindingsWithSpeech,
  proveOfflineEdgeSttBinding,
  type OfflineEdgeSttTelemetry,
  type ProveOfflineEdgeSttOptions,
  type ProveOfflineEdgeSttResult,
} from "./edge_stt_harness.js";

export {
  DEFAULT_SPEECH_CERT_PROFILE,
  DEFAULT_SPEECH_CERT_REPORT,
  SPEECH_CERT_OBLIGATION_IDS,
  SPEECH_CERT_REPORT_SCHEMA_VERSION,
  SPEECH_PACKAGE_ROOT,
  loadSpeechCertProfile,
  parseSpeechCertArgv,
  proveSpeechCertificationGate,
  runIndicFixtureGate,
  runSpeechCertCli,
  runSpeechCertification,
  type ProveSpeechCertResult,
  type RunSpeechCertificationOptions,
  type SpeechCertBindingId,
  type SpeechCertBindingResult,
  type SpeechCertIo,
  type SpeechCertProfile,
  type SpeechCertReport,
} from "./speech_certification.js";

export {
  DEFAULT_VOICE_RTT_BASELINE,
  DEFAULT_VOICE_RTT_DEVICE_PROFILE,
  NFR_07_BUDGET_P95_MS,
  NFR_07_ID,
  createDelayedFirstAudioTtsBackend,
  evaluateVoiceRttGates,
  loadVoiceRttBaseline,
  loadVoiceRttDeviceProfile,
  measureOneVoiceRttSample,
  percentileMs,
  runVoiceRttProof,
  type RunVoiceRttProofOptions,
  type VoiceRttBaseline,
  type VoiceRttDeviceProfile,
  type VoiceRttProofResult,
  type VoiceRttSample,
} from "./voice_rtt_proof.js";

export {
  DEFAULT_TTS_MODEL_CARD,
  DEFAULT_TTS_VOICES_MANIFEST,
  LOCAL_TTS_ENGINE,
  TTS_PACKAGE_ROOT,
  TTS_SAMPLE_RATE_HZ,
  TTS_STREAM_CHUNK_LIMIT,
  TTS_TEXT_CHAR_LIMIT,
  LocalTtsBinding,
  LocalTtsError,
  assertTtsModelCardMatchesVoices,
  createInProcessLocalTtsBackend,
  createLocalTtsSpeechHarnessFactory,
  languageVoiceCoverageTable,
  languagesFromVoices,
  loadLocalTts,
  loadTtsVoiceModelCard,
  loadTtsVoicesManifest,
  resolveTtsVoice,
  type CreateLocalTtsSpeechHarnessOptions,
  type LoadLocalTtsOptions,
  type LocalTtsNativeBackend,
  type LocalTtsNativeHandle,
  type LocalTtsSynthesizeNativeParams,
  type LocalTtsSynthesizeNativeResult,
  type LocalTtsTelemetryEvent,
  type LocalTtsTelemetryOp,
  type TtsLanguageVoiceCoverageRow,
  type TtsVoiceCard,
  type TtsVoiceModelCard,
  type TtsVoicesManifest,
} from "./tts_binding.js";
